### PR TITLE
NuGet validation updates.

### PR DESCRIPTION
**Pull request by v-ddennis**

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2621) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2621) before we can accept your contribution.<br/><br/>:x: v-ddennis [sign now](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2621)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/docs.microsoft.com-nuget?pullRequest=2621) it.</sub>

**Comment by v-ddennis** [comment]
#sign-off

**Comment by JonDouglas** [comment]
These updates do not seem like they improve our docs. Many of these elements that look like XML are just examples for the reader to fill in similar to arguments in a command line. I do not believe we should take these changes.

**Comment by JonDouglas** [comment]
Can we get a quick description of these validations & understanding what's being added here? Thanks!

**Comment by zivkan** [comment]
@JonDouglas in markdown, unless XML is inside a code block, then it gets parsed as HTML, but there's an allow-list of which HTML elements are allowed and everything else gets stripped out.

If you have a look at https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#troubleshooting-errors, you don't see the `<package>`  string.
If you click the preview URL link from the docs bots, you will see it.

**Comment by JonDouglas** [comment]
Thanks @zivkan,

I was mostly hopeful to understand the intention of the PR as it has no description and these types of PRs are ran through a tool. Fine to merge for now.

**Review by JonDouglas — APPROVED** [review]
Thanks for the contribution!

**Comment by zivkan** [comment]
@JonDouglas I agree. Creating a PR without providing any description increases our workload because we have to try to figure out what the intention is.

**Pull request merged**
