### PR TITLE
[BrokenLinksH2]

### PR DESCRIPTION
**Pull request by mohitp930**

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2781) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2781) before we can accept your contribution.<br/><br/>:x: mohitp930 [sign now](https://cla.dotnetfoundation.org/NuGet/docs.microsoft.com-nuget?pullRequest=2781)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/docs.microsoft.com-nuget?pullRequest=2781) it.</sub>

**Comment by mohitp930** [comment]
Global effort to fix broken links

@kartheekp-ms 

[Note] codeplex.com is a defunct side, and Microsoft seems to no longer host the archive. So I've opted to remove any outbounds links to the site. If an alternative solution exists, I'll be happy to make the change.

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Comment by mohitp930** [comment]
@JonDouglas Do you have suggestions for this pr for it to get merged?

**Comment by JonDouglas** [comment]
@mohitp930 In the current form I do not feel comfortable merging. We are removing links to just about every NuGet release which makes it hard for people to historically track down archives if they were curious. People would now have to go through commit history to find them. I know that I have used dead links in previous releases in the past to understand more context, so I don't think we should simply remove these dead links if at one point in history they were active ones. 

I've added more reviewers in the meantime for more thoughts.

**Comment by mohitp930** [comment]
Makes sense. In that case I'm fine to close the pr and see if I can leave a note a note for future broken links efforts to give special consideration to the nuget repo. I'll wait for a little while though to see if anyone else has other thoughts.

**Review by dominoFire — COMMENTED** [review]
I am comfortable accepting this PR without changes in:
- release notes,
- team foundation build
- known issues

**Comment by nkolev92** [comment]
Closing the PR per the above discussion. 
Feel free to reopen if necessary.

**Pull request closed without merging**
