### PR TITLE
Push required client 

### PR DESCRIPTION
**Pull request by anangaur**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710042147156312-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BFCRS9Jx08FREjPYz2IS0Viq3jwsACSUWL8XQFwNOVk%3D&st=2017-10-04T21%3A42%3A57Z&se=2017-10-05T21%3A52%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710042148565173-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uUwB4GAM%2BUn2y72LtSOgHK5PucmdKpfWuyrvsMZ5YbQ%3D&st=2017-10-04T21%3A44%3A33Z&se=2017-10-05T21%3A54%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710042150552128-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CFkxm51HsoV0wuaJ4wwNDFWMwEr8ZmTfJF%2Ffg8%2FI7V0%3D&st=2017-10-04T21%3A46%3A36Z&se=2017-10-05T21%3A56%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710042214308407-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ivtFa1XKZoGVQvz1FU7A6ny4Gpph1oymgKzi%2FWhnP1o%3D&st=2017-10-04T22%3A10%3A35Z&se=2017-10-05T22%3A20%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051901228813-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rtAufvv0kpA5zIyGSpDkJUbIalIeKsen9FtGZwvqids%3D&st=2017-10-05T18%3A57%3A04Z&se=2017-10-06T19%3A07%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051902136836-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HTT19tzzHImT0EWABP5bl1nNQ8JBwNn2YJKt%2Bls5F%2F4%3D&st=2017-10-05T18%3A58%3A06Z&se=2017-10-06T19%3A08%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051903390484-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sM0TuuINuLl2zzWvuH5YxKXnbFYiiR9rhhmDKa4Wu1M%3D&st=2017-10-05T19%3A00%3A07Z&se=2017-10-06T19%3A10%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051905021891-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cmfwDpR3Z%2BUFwBuqP28JD%2B3ohN%2BN7O2W984N3nU69uU%3D&st=2017-10-05T19%3A00%3A57Z&se=2017-10-06T19%3A10%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051907326070-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2PLQ9aAI8t0UxWnwO%2FHlbGQPmQLDNdkX1NcAH0cEfAc%3D&st=2017-10-05T19%3A03%3A19Z&se=2017-10-06T19%3A13%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051908111216-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ObHMXYfLLFS8RopU5YFBeQNlfmAb4OzSG9IGhin86Cg%3D&st=2017-10-05T19%3A04%3A04Z&se=2017-10-06T19%3A14%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@anangaur Can you review my edits here? I believe you meant to say that nuget.exe 4.3.0 is required for nuget.org, but is that true for all other package sources? I wouldn't think it is, so my edits make it clear that the requirement is for nuget.org specifically.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710051908374286-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zU%2Flxi0aAtY1e5WLT%2BY3IBHSSIecw4wat%2Bww%2FampxCs%3D&st=2017-10-05T19%3A04%3A47Z&se=2017-10-06T19%3A14%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062237308549-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kjXL%2B4%2BrcRlIR9UEnQoFUVJDN3W3gYgccH0cHXe3IK4%3D&st=2017-10-06T22%3A33%3A14Z&se=2017-10-07T22%3A43%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062238296610-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FUNin9m7PC94xHthm5vsnP%2Bn0yB7YLUEMUiTVT3n8Ek%3D&st=2017-10-06T22%3A34%3A34Z&se=2017-10-07T22%3A44%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062239038215-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=k0lOLAV6jcaig4V97%2BaMEOZA1BTquX95n%2BT0jpFU4sQ%3D&st=2017-10-06T22%3A36%3A06Z&se=2017-10-07T22%3A46%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062242198941-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2ZtZqaMlsZjA4Lsyufkka9lsrakbaVIbUtGLIcnQ0pU%3D&st=2017-10-06T22%3A38%3A00Z&se=2017-10-07T22%3A48%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062242548215-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BBkKkha9waNCJ%2FJGW5o6qxEYrPrm1Xzxhq83MSSkWt8%3D&st=2017-10-06T22%3A38%3A40Z&se=2017-10-07T22%3A48%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062243351111-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tQPqxlMYGm5%2BRZ36%2BTxwdEgjx9XOgs3tr35zB3tJaK8%3D&st=2017-10-06T22%3A39%3A30Z&se=2017-10-07T22%3A49%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Create-Packages/Symbol-Packages.md) | :white_check_mark:Succeeded | |
[docs/Tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-push-requirement/docs/Tools/nuget-exe-CLI-Reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710062243564911-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Cs118ZSk12Xt0y5xD2Ruhxgq15Tz9Zd%2FsaOjRzdj%2FiE%3D&st=2017-10-06T22%3A40%3A24Z&se=2017-10-07T22%3A50%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anangaur** [comment]
@kraigb makes sense. I have updated the text. I will be merging these in now.

**Pull request merged**
