### PR TITLE
Update NuGet-2.0.md

### LINKED ISSUE #1093: Misleading information in dependencies-element
The dependencies-element attributes table states that both id and version are required while example in dependency groups section below shows example without version:

    <group targetFramework="net40">
        <dependency id="jQuery" />
        <dependency id="WebActivator" />
    </group>

## Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 06a19d7d-253d-f17f-6421-624c9867473d
Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
Content: .nuspec File Reference for NuGet
Content Source: docs/reference/nuspec.md

### PR DESCRIPTION
**Pull request by JSmurf**
Added version numbers to dependencies which were missing them. Attempting to resolve #1093.

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/release-notes/NuGet-2.0.md](https://github.com/JSmurf/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-2.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-2.0?branch=pr-en-us-1096) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C16%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201810161634169585-1096%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nDqIzXpShGSyQnGvI3LQ9R1l0Wz7lMfABS9xBmsgsfM%3D&st=2018-10-16T16%3A30%3A26Z&se=2018-11-16T16%3A35%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@JSmurf you are attempting to update the wrong doc.

**Comment by JSmurf** [comment]
@karann-msft That was the only document I could find that had the code snippet included in the issue. I will look again and see if I can find where the original issue was referring to.

**Comment by karann-msft** [comment]
@JSmurf we seldom update release notes. They are a point in time doc that is meant for that specific release.

For docs issues, you can always find out the associated docs page by looking at the Content and Content source.

Content: .nuspec File Reference for NuGet
Content Source: docs/reference/nuspec.md

https://docs.microsoft.com/en-us/nuget/reference/nuspec

**Pull request closed without merging**
