### PR TITLE
Update Restore.md

### PR DESCRIPTION
**Pull request by karann-msft**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240306137601-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=acC0TMdn1PEQAMnfkKhCds9983Eph1bY%2FY6gqmsCTzw%3D&st=2017-10-24T03%3A01%3A53Z&se=2017-11-24T03%3A06%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240343581659-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=adaWs3G8ATMlWkwqvrFUAwymoNwkN4FwV8Ie3MNSvgc%3D&st=2017-10-24T03%3A39%3A34Z&se=2017-11-24T03%3A44%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240347498711-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pnWcFTsdFCs3Kbk%2B0qvr5cZ%2BwGYww07pNlI1Io5eGe4%3D&st=2017-10-24T03%3A43%3A30Z&se=2017-11-24T03%3A48%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240427346790-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0L896bDsTP3RgNXABTRSK8V0TQxaq5Ugv%2BeyLkJSYJw%3D&st=2017-10-24T04%3A32%3A56Z&se=2017-11-24T04%3A37%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240442294970-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lE7oVGnTS0p7Gc2Aphuvqs0PFUlQ91X%2Fa06O7fz3P3U%3D&st=2017-10-24T04%3A42%3A43Z&se=2017-11-24T04%3A47%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240742285697-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=syqtmMRwVk40BHEHCZ1WpaYisLiBHaGEYgbRPw96XRA%3D&st=2017-10-24T07%3A38%3A07Z&se=2017-11-24T07%3A43%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 44**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710240757579007-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QoXq%2F733I6lsc5msZDh0ttuxnvvy5rEecZcZmF7v%2F40%3D&st=2017-10-24T07%3A53%3A40Z&se=2017-11-24T07%3A58%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@kraigb I tried both  "Extending the Package Manager Console" and "Setting up a NuGet PowerShell Profile'. Neither works. In the first case, the package installation fails. In the second one, the profile doesn't exist. Need to confirm if these scenarios are still supported.
Also, there was content in there about cache and project.asset.json. That file is not the cache. I tried clarifying that a bit.
Also, uninstalling a package doesn't remove it from the cache. It does however remove the reference to it and also from the project.asset.json file a.k.a lock file.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 45**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710241635480704-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SwQOktKSvlflAeUMKUfXdWcFpROLuMoRRfKFESpggBk%3D&st=2017-10-24T16%3A31%3A25Z&se=2017-11-24T16%3A36%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :warning:Warning | | [Details](#user-content-docs%2FQuickstart%2FRestore.md)
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

<a name="docs%2FQuickstart%2FRestore.md"></a>
### [docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md)
 - **Line 45**: **[Warning]** Invalid file link:(~/Consume-Packages/Package-Restore#enabling-and-disabling-package-restore).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710241641425306-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BtaiDTWVL1iEXENzUouX495YiyRHfsrokVvcgZhL8tY%3D&st=2017-10-24T16%3A37%3A23Z&se=2017-11-24T16%3A42%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :white_check_mark:Succeeded | |
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710241644064880-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YmGbtT6rdpZuemKZb5lDxwAZxvhOhfy3ZTn%2Bxdmt0kg%3D&st=2017-10-24T16%3A39%3A47Z&se=2017-11-24T16%3A44%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Quickstart/Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Quickstart/Restore.md) | :white_check_mark:Succeeded | |
[docs/Tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-fwlink/docs/Tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710241645093080-522%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oGagesjwzwvlTsCiC5PiCCoylspkFtrr225txMx7jwk%3D&st=2017-10-24T16%3A40%3A48Z&se=2017-11-24T16%3A45%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
