### PR TITLE
Update to add support for newer versions of VS

### PR DESCRIPTION
**Pull request by skendrot**
Migrated projects are not limited to 2017, Update the docs to say that they are supported in 2017 and newer

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[34d2659](https://github.com/skendrot/docs.microsoft.com-nuget/pull/1520/commits/34d2659af23cd8afcd067211fd231c0bd0b04dcd)_: 

:clock10: **Pending**: waiting for processors ([24](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 24 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[34d2659](https://github.com/skendrot/docs.microsoft.com-nuget/pull/1520/commits/34d2659af23cd8afcd067211fd231c0bd0b04dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/skendrot/docs.microsoft.com-nuget/blob/patch-2/docs/reference/migrate-packages-config-to-package-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference?branch=pr-en-us-1520) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C8%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907081820331617-1520%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UIoLFbJHXcyLD0By1mLhYPNaqxNGjGu4zt7Jx2c3UI8%3D&st=2019-07-08T18%3A16%3A24Z&se=2019-08-08T18%3A21%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
thanks for the PR @skendrot. This has been addressed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1564

**Comment by skendrot** [comment]
This is really disappointing. A PR is submitted, and rather than accept that one, or request changes a new PR is submitted and merged?!?

**Comment by karann-msft** [comment]
hey @skendrot - that was totally not the intention. It is just the order in which the PR was merged. That PR happened to get merged before we realized there was an older PR with the exact change. In hindsight, we should go from the oldest to the newest and then we would have merged this one and closed the other one. Again, I apologize and I understand how this might have made you feel.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[34d2659](https://github.com/skendrot/docs.microsoft.com-nuget/pull/1520/commits/34d2659af23cd8afcd067211fd231c0bd0b04dcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7cb390ce)

<a id="7cb390ce"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/NuGet/docs.microsoft.com-nuget, working directory: W:\gczz-s, target branch: master, target branch commit: 0412d2c1b5650233d6dd18da6f968c4bfa0a5776, source commit: 34d2659af23cd8afcd067211fd231c0bd0b04dcd.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C26%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907261818203192-1520%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xdJ1KZnJCllo000%2BRKmBQeBUjedoXfBQdsOOebkDeKI%3D&st=2019-07-26T18%3A13%3A32Z&se=2019-08-26T18%3A18%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[7aee7c3](https://github.com/skendrot/docs.microsoft.com-nuget/pull/1520/commits/7aee7c3cf843511159839efcc31e082292bae576)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C26%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907261818575999-1520%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rRZ4lgzO6fG5anfyhdPQBNRlE6E8uEOxBsyqFcpZxJA%3D&st=2019-07-26T18%3A14%3A56Z&se=2019-08-26T18%3A19%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
