### PR TITLE
Created new page "Extending the Package Manager Console"

### PR DESCRIPTION
**Pull request by samrueby**
It was difficult to find any information on Init.ps1, Install.ps1, and Uninstall.ps1 that wasn't just mentioned in blog posts from years ago. Users also wouldn't know that Install.ps1 and Uninstall.ps1 are deprecated without digging through github issues. Because those two are deprecated, it was difficult to find out if Init.ps1 is also on the chopping block. I confirmed that it is not.

Issue: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1380

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[1a64a73](https://github.com/samrueby/docs.microsoft.com-nuget/pull/1390/commits/1a64a73cec1fa31a1c1fbf5ea07009e76e51c692)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/create-packages/Extending-the-Package-Manager-Console.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/create-packages/Extending-the-Package-Manager-Console.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/extending-the-package-manager-console?branch=pr-en-us-1390) | [Details](#user-content-d8fa8448-f8b15cf6)
[docs/reference/analyzers-conventions.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/reference/analyzers-conventions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/reference/analyzers-conventions?branch=pr-en-us-1390) | [Details](#user-content-f1fbab3c-f8b15cf6)
[docs/TOC.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/analyzers-conventions?branch=pr-en-us-1390) |
[docs/tools/Package-Manager-Console.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/tools/Package-Manager-Console.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/package-manager-console?branch=pr-en-us-1390) |

<a id="d8fa8448-f8b15cf6"></a>
### [docs/create-packages/Extending-the-Package-Manager-Console.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/create-packages/Extending-the-Package-Manager-Console.md)
 - **Line 0**: **[Warning]** Text in the first line of Note/Section/Video is not valid. Will be rendererd to &lt;blockquote&gt;
 - **Line 0**: **[Warning]** Text in the first line of Note/Section/Video is not valid. Will be rendererd to &lt;blockquote&gt;
 - **Line 0**: **[Warning]** Text in the first line of Note/Section/Video is not valid. Will be rendererd to &lt;blockquote&gt;
 - **Line 16**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#init.ps1&quot;&gt;Init.ps1&lt;/a&gt;` -- missing bookmark. The file create-packages/Extending-the-Package-Manager-Console.md doesn&#39;t contain a bookmark named init.ps1.
 - **Line 17**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#install.ps1&quot;&gt;Install.ps1&lt;/a&gt;` -- missing bookmark. The file create-packages/Extending-the-Package-Manager-Console.md doesn&#39;t contain a bookmark named install.ps1.
 - **Line 18**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#Uninstall.ps1&quot;&gt;Uninstall.ps1&lt;/a&gt;` -- missing bookmark. The file create-packages/Extending-the-Package-Manager-Console.md doesn&#39;t contain a bookmark named Uninstall.ps1.

<a id="f1fbab3c-f8b15cf6"></a>
### [docs/reference/analyzers-conventions.md](https://github.com/samrueby/docs.microsoft.com-nuget/blob/live/docs/reference/analyzers-conventions.md)
 - **Line 0**: **[Warning]** Text in the first line of Note/Section/Video is not valid. Will be rendererd to &lt;blockquote&gt;

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201904061552046231-1390%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5O4hYPDjcsEeOihc77vLiAG2SAqCx9Fn79cQRLGXdsw%3D&st=2019-04-06T15%3A48%3A28Z&se=2019-05-07T15%3A53%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by samrueby** [comment]
I followed advice on StackOverflow that this was an appropriate way to link to bookmarks on the page. I didn't see a mention of how to properly create bookmarks in the main README for the repo.

**Comment by karann-msft** [comment]
@samrueby - thanks for the PR. It is being reviewed.

**Comment by zivkan** [comment]
Just curious, how/why did you come to use the live branch? The repo's default branch is master, which is where changes should go. I'm confused every time I see a community contribution that asks to be merged into live.  I'll change it, but I don't know why it's happening.

**Comment by samrueby** [comment]
Thank you! Let me know how I can help.

https://github.com/NuGet/docs.microsoft.com-nuget :
> Contributions to this docset are welcome. **Please submit PRs to the live branch**, which is what's published to the live docs site. (The master branch is used for staging larger series of changes.)

**Pull request closed without merging**
