### PR TITLE
M19261: Ambiguity: Unknown concept - light-up

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hellom @kraigb, 

Translator has reported possible source content issue.  

Please, help to check my comment tag added into the article and reply with explanation if source text should be fixed, or it is by design. If fix is needed, please, let me know either if you would like me to fix it in this PR, or if you will fix it in another PR. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR. 

Many thanks in advance.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/archive/project-json-and-uwp.md](https://github.com/carolinacmoravia/docs.microsoft.com-nuget/blob/patch-2/docs/archive/project-json-and-uwp.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201802051710546917-689%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g0R9eLvLlSjxQd7UMadh7eON%2BeioD%2BhefX5H2aslhLQ%3D&st=2018-02-05T17%3A07%3A16Z&se=2018-03-08T17%3A12%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
To answer the question, "light-up" refers to features being enabled under certain conditions. In the header under question, change "Native light-up" to "Enabling specific native features" and it should translate better

**Comment by kraigb** [comment]
Adding the do-not-merge flag pending removal of the comment in the text.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/archive/project-json-and-uwp.md](https://github.com/carolinacmoravia/docs.microsoft.com-nuget/blob/patch-2/docs/archive/project-json-and-uwp.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C27%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201802270048344197-689%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yh1NfBg4UNDL80T3NocLOmDEd7%2FWdtLFIVLztNLuAFI%3D&st=2018-02-27T00%3A44%3A25Z&se=2018-03-30T00%3A49%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
