### PR TITLE
release-notes/NuGet-5.6.md: fix issues fixed link

### PR DESCRIPTION
**Pull request by fowl2**
replace ZenHub (private?) link with GitHub (public) one

### CODE REVIEW

**Comment by anangaur** [comment]
Docs Build status updates of commit _[c1017cc](https://github.com/fowl2/docs.microsoft.com-nuget/commits/c1017ccf88248ecf9c5a33252c9e03a6fa48bac3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/release-notes/NuGet-5.6.md](https://github.com/fowl2/docs.microsoft.com-nuget/blob/patch-2/docs/release-notes/NuGet-5.6.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-5.6?branch=pr-en-us-2052) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C26%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202005260115118385-2052%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VzlEi%2B%2FOxu7Q2lA1EjJ4YVH9311zKpI491OYCgSMMuk%3D&st=2020-05-26T01%3A11%3A05Z&se=2020-06-26T01%3A16%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by nkolev92** [comment]
Hey @fowl2 

Thanks for the contribution. 
Unfortunately that link is not quite up to date. 

We are now using ZenHub to track our releases as covered in https://github.com/NuGet/Home/blob/dev/designs/ClientDevProcess.md#release-tracking.

**Comment by fowl2** [comment]
@nkolev92 so the fixed issue information is private now?

**Comment by nkolev92** [comment]
It's not private. You just need the zenhub installed.

cc @zkat @aortiz-msft

**Comment by fowl2** [comment]
Is there a way to view the data without providing these permissions? This is waaaay too much access. GitHub doesn't even require an account to view the data.

image

**Comment by nkolev92** [comment]
@fowl2 

Unfortunately not a full list right now. 
We can consider including the complete list of issues in a different way. 

@fowl2 I created an issue at https://github.com/NuGet/Home/issues/9908 to have this discussion. 

This experience is a consequence of our larger process.

**Pull request closed without merging**
