### PR TITLE
Merge main into live branch

### PR DESCRIPTION
**Pull request by donnie-msft**

### CODE REVIEW

**Comment by donnie-msft** [comment]
I'll close this since I already have another PR open that will need merged to `live` as well: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3084

**Review by nkolev92 — APPROVED** [review]
cc @JonDouglas who usually handles this.

**Comment by zivkan** [comment]
I thought merging to live only gets deployed if the person who created & merges the PR is on an allow-list?  Therefore, merging this PR won't deploy?

**Comment by donnie-msft** [comment]
> I thought merging to live only gets deployed if the person who created & merges the PR is on an allow-list?  Therefore, merging this PR won't deploy?

The readme seems pretty flexible and just says to create the PR. If that's the case, maybe whoever is on this allow list can update the readme.

**Comment by lyndaidaii** [comment]
> > I thought merging to live only gets deployed if the person who created & merges the PR is on an allow-list?  Therefore, merging this PR won't deploy?
> 
> The readme seems pretty flexible and just says to create the PR. If that's the case, maybe whoever is on this allow list can update the readme.

mine changes look like are alive already

**Comment by donnie-msft** [comment]
@nkolev92 & @zivkan, Jon replied offline Friday that we are able to create this PR ourselves and without his approval. 
This PR can be merged so long as either of you didn't merge a docs PR that you actually didn't want live yet?

Lynn seems good with this being merged, and is the only other commit author in this PR.

**Pull request merged**
