### PR TITLE
Delete orphaned files

### PR DESCRIPTION
**Pull request by gewarren**
- orphaned markdown files (4)
- orphaned images (27)

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[0a41fe9](https://github.com/gewarren/docs.microsoft.com-nuget/commits/0a41fe9b82715fd4b5f5d3890b9bbcb1b4c363d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/archive/config-priority-order.md](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/archive/config-priority-order.md) | :white_check_mark:Succeeded | |
[docs/archive/project-json-archive.md](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/archive/project-json-archive.md) | :white_check_mark:Succeeded | |
[docs/archive/readme.md](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/archive/readme.md) | :white_check_mark:Succeeded | |
[docs/consume-packages/media/Finding-05-OperationChart.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/consume-packages/media/Finding-05-OperationChart.png) | :white_check_mark:Succeeded | |
[docs/consume-packages/media/PackageManagerConsoleControls.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/consume-packages/media/PackageManagerConsoleControls.png) | :white_check_mark:Succeeded | |
[docs/consume-packages/media/Restore-02-VSTSBuild.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/consume-packages/media/Restore-02-VSTSBuild.png) | :white_check_mark:Succeeded | |
[docs/consume-packages/media/Symbols_01-AddingSource.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/consume-packages/media/Symbols_01-AddingSource.png) | :white_check_mark:Succeeded | |
[docs/create-packages/media/publish_APIKey.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/create-packages/media/publish_APIKey.png) | :white_check_mark:Succeeded | |
[docs/guides/media/BetaChannel-ExtensionUpdate.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/guides/media/BetaChannel-ExtensionUpdate.png) | :white_check_mark:Succeeded | |
[docs/guides/media/BetaChannel-ToolsSettings.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/guides/media/BetaChannel-ToolsSettings.png) | :white_check_mark:Succeeded | |
[docs/guides/media/NuGet4-01-Workload.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/guides/media/NuGet4-01-Workload.png) | :white_check_mark:Succeeded | |
[docs/guides/media/NuGet4-02-NewProject.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/guides/media/NuGet4-02-NewProject.png) | :white_check_mark:Succeeded | |
[docs/guides/media/NuGet4-03-PackageExplorer.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/guides/media/NuGet4-03-PackageExplorer.png) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-consume-packages.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-consume-packages.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-create-packages.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-create-packages.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-guides.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-guides.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-host-packages.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-host-packages.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-quickstarts.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-quickstarts.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-get-started-what-is-nuget.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-get-started-what-is-nuget.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-tools-api.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-tools-api.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-tools-policies.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-tools-policies.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-tools-reference.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-tools-reference.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-tools-tools.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-tools-tools.svg) | :white_check_mark:Succeeded | |
[docs/media/hub/nuget-tools-vs-extensibility.svg](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/media/hub/nuget-tools-vs-extensibility.svg) | :white_check_mark:Succeeded | |
[docs/quickstart/media/QS_Create-01-NewProject.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/QS_Create-01-NewProject.png) | :white_check_mark:Succeeded | |
[docs/quickstart/media/QS_Restore-01-ToolsOptions.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/QS_Restore-01-ToolsOptions.png) | :white_check_mark:Succeeded | |
[docs/quickstart/media/QS_Use-01-NewProject.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/QS_Use-01-NewProject.png) | :white_check_mark:Succeeded | |
[docs/quickstart/media/QS_Use-04-ShowPotentialFixes.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/QS_Use-04-ShowPotentialFixes.png) | :white_check_mark:Succeeded | |
[docs/quickstart/media/QS_Use-05-AddUsing.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/QS_Use-05-AddUsing.png) | :white_check_mark:Succeeded | |
[docs/quickstart/media/new-project-vs-mac.png](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/quickstart/media/new-project-vs-mac.png) | :white_check_mark:Succeeded | |
[docs/release-notes/NuGet-5.0-preview.md](https://github.com/gewarren/docs.microsoft.com-nuget/blob/orphans/docs/release-notes/NuGet-5.0-preview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C7%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202001070105188939-1833%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hsZ3uj7wVTQ6JiH5Rwu%2Ba6oHOw732DDbnxI%2BBN0wyGg%3D&st=2020-01-07T01%3A02%3A33Z&se=2020-02-07T01%3A07%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gewarren** [comment]
@karann-msft Since I'd cloned the repo, I ran some of the other clean up features of the CleanRepo tool and created this PR.

**Comment by karann-msft** [comment]
Thank you @gewarren!!!

**Comment by karann-msft** [comment]
@Mikejo5000 - can you take a quick peek at this PR. Thanks!

**Pull request merged**
