### PR TITLE
Added NuGet video "What is NuGet?"

### PR DESCRIPTION
**Pull request by chgill-MSFT**
In the preview it doesn't show the video, but it seems to appear fine when published. This is the exact type of embedding used in other docs with videos such as: 
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/includes/xamarin-show-essentials.md

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[721ccd6](https://github.com/NuGet/docs.microsoft.com-nuget/commits/721ccd6fb4507824eb8c9ff31047655482b3e7ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-1/docs/what-is-nuget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/what-is-nuget?branch=pr-en-us-1881) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002102147282702-1881%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z26ROMMl8Xkqo4sf%2Fws140efdACJsqD5mBlNFWYEBdg%3D&st=2020-02-10T21%3A43%3A03Z&se=2020-03-12T21%3A48%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
I would imagine the video to be the first thing on the doc.... not the last.... 
@chgill-MSFT - can you point to other docs that embed videos...
cc: @anangaur

**Comment by anangaur** [comment]
It would be good to link the **review** URL to preview the proposed changes. 

+1 to @karann-msft 's comment to add the video to the top.

**Comment by karann-msft** [comment]
The preview URL is available as part of the validation status message above

image

**Comment by anangaur** [comment]
Wow. Never noticed that. Thanks for letting me know :)

**Comment by chgill-MSFT** [comment]
@karann-msft @anangaur putting this video first was my initial inclination, but when I asked Jayme for existing examples she pointed me to these:

- [Example 1](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/deepdive?pivots=windows#related-video)
- [Example 2](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#related-video)
- [Example 3](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class#related-video)
- [Example 4](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm#related-videos)
- [Example 5](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/index#related-video)

They're all Xamarin examples since I think they're one of the first to integrate videos into their docs. If we want to deviate from their style I think that'll be fine since most docs don't have videos, so we won't be "going against the grain" in terms of Microsoft styling.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[1c484eb](https://github.com/NuGet/docs.microsoft.com-nuget/commits/1c484eba7431e4f2ca6db3b37166f3461655048d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-1/docs/what-is-nuget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/what-is-nuget?branch=pr-en-us-1881) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002192201388404-1881%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X2xn8IGUO1364IE751ZjnPmJDkYGpgTvltbr9pS77Bk%3D&st=2020-02-19T21%3A57%3A17Z&se=2020-03-21T22%3A02%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
