### PR TITLE
Doc AssetTargetFallback in package compat section

### PR DESCRIPTION
**Pull request by rrelyea**
Better place to put this. Good start? What else is important to say?

### CODE REVIEW

**Comment by karann-msft** [comment]
OPS Build status updates of commit _[e4c6ab0](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1264/commits/e4c6ab0d367f32a18d61789e16aa32ba1e1a3fcd)_: 

:clock10: **Preparing**: average preparing time is _39 sec(s)_

**Comment by karann-msft** [comment]
OPS Build status updates of commit _[e4c6ab0](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1264/commits/e4c6ab0d367f32a18d61789e16aa32ba1e1a3fcd)_: 

:clock10: **Incremental building**: average incremental building time is _21 sec(s)_

**Comment by karann-msft** [comment]
OPS Build status updates of commit _[e4c6ab0](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1264/commits/e4c6ab0d367f32a18d61789e16aa32ba1e1a3fcd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/rrelyea-assetTargetFallbackBriefDescription/docs/consume-packages/Finding-and-Choosing-Packages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1264) | [Details](#user-content-docs%2Fconsume-packages%2FFinding-and-Choosing-Packages.md)

<a name="docs%2Fconsume-packages%2FFinding-and-Choosing-Packages.md"></a>
### [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/rrelyea-assetTargetFallbackBriefDescription/docs/consume-packages/Finding-and-Choosing-Packages.md)
 - **Line 102**: **[Warning]** Invalid file link:(~/reference/nuspec#licenseurl).
 - **Line 102**: **[Warning]** Invalid file link:(~/reference/nuspec#license).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C15%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201901151622144661-1264%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z8m5pCe9qkHOe3dLSjerxjrU9qwSwEFUiRM%2BCJdTzjY%3D&st=2019-01-15T16%3A18%3A46Z&se=2019-02-15T16%3A23%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@rrelyea it is not clear why and in what situation should someone use this property. You'd need to provide specific use cases for using this back door entry into installing a package that was determined to be incompatible by the client based on TFM.

**Comment by anangaur** [comment]
I agree with @karann-msft . I feel this should go somewhere in Reference docs and not in the main line "Consume packages" scenario doc.

**Comment by rrelyea** [comment]
I'll look for a place to hide it more...

**Pull request closed without merging**
