### PR TITLE
GitHub issues

### PR DESCRIPTION
**Pull request by Mikejo5000**

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[8d1edd6](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1562/commits/8d1edd6c754f67cb22eb4d81129c8d9f463bcb64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/let-this-app-access.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/let-this-app-access.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/let-this-app-surface.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/let-this-app-surface.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907222229307198-1562%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nb6W%2BYIGPBwKm%2FH%2BCNzjv5r1EPkt7%2FNt8oZjG%2FMuQis%3D&st=2019-07-22T22%3A25%3A27Z&se=2019-08-22T22%3A30%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[3273fad](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1562/commits/3273fad586dc54de2142d977e88d992fe4e03fbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/let-this-app-access.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/let-this-app-access.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/let-this-app-surface.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/let-this-app-surface.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907222238258695-1562%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lyW4HZRMT%2BZFZouARYGkXx67AiisgFiyrMbV6PrlJfY%3D&st=2019-07-22T22%3A34%3A20Z&se=2019-08-22T22%3A39%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[5ab3aa7](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1562/commits/5ab3aa7b132a33d5cb4118a9ee106fdb4cc79038)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-enter-code-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-enter-code-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-register-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-register-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-sign-in-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-sign-in-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907222341190838-1562%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3hc6PxdowOo5TIZPM9BEjLO0xujSGL2BNT%2Fb4zfcSgc%3D&st=2019-07-22T23%3A37%3A12Z&se=2019-08-22T23%3A42%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[974d5cf](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1562/commits/974d5cf59b3e1204586025b6a509cb12170edf81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-enter-code-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-enter-code-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-register-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-register-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-sign-in-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-sign-in-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/quickstart/includes/publish-api-key.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/quickstart/includes/publish-api-key.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1562) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907222350402788-1562%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f0NdlYNwPPgctzIxYeJB6MAyqVs00zKaB18VvjfwRsk%3D&st=2019-07-22T23%3A46%3A37Z&se=2019-08-22T23%3A51%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[f3f2383](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1562/commits/f3f2383e4b843b70b7aebd0fa2bba9dfb7f56022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-enter-code-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-enter-code-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-register-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-register-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/nuget-org/media/nuget-org-sign-in-2fa.png](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/nuget-org/media/nuget-org-sign-in-2fa.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1562) |
[docs/quickstart/includes/publish-api-key.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-2fa/docs/quickstart/includes/publish-api-key.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1562) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907222354416398-1562%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=unPPuC0XGh4yx8yVPV7JJzM8CrQ4GD3IMXwIBTogVKo%3D&st=2019-07-22T23%3A50%3A35Z&se=2019-08-22T23%3A55%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
