### PR TITLE
remove JSON from resource build scope

### PR DESCRIPTION
**Pull request by 928PJY**
This fix is for migration to docfx v3.
we remove the JSON files from resource build scope since the JSON files are only used as code snippets in this repository, it don't need to be added to resource scope unless you want to publish those JSON files and access it by URL.

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[2942c73](https://github.com/928PJY/docs.microsoft.com-nuget/commits/2942c735310affafe6d82ef008afb5020226e64d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docfx.json](https://github.com/928PJY/docs.microsoft.com-nuget/blob/config/docs/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C7%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201908070131066069-1602%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n0by9GlTOb6QBOqQ4dU0AkDbBu0evyMDbMyhnBLwl%2B4%3D&st=2019-08-07T01%3A27%3A04Z&se=2019-09-07T01%3A32%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@928PJY - what is the impact of this change?

**Comment by Mikejo5000** [comment]
@karann-msft The effect of this change is unclear to me, but I do notice that VS doesn't have *.json in this resource list either.

**Comment by 928PJY** [comment]
@karann-msft @Mikejo5000 This fix won't bring any impact to your published content page, the only impact is that you can not access those json files by URL `https://docs.microsoft.com/xxx/x.json`, but we think that is not a normal requirement. 
The reason why we need this fix is we are going to migrate this repository from docfx v2 to v3, by migrating to docfx v3, you will get a much better build performance(for this specific repository, the build time will be changed from 126s to 31s), but the JSON file is not supported to published as resource file anymore in docfx v3.

**Pull request merged**
