### PR TITLE
Update service index API docs to specify 3.0.0 instead of 3.0.0-beta.1

### PR DESCRIPTION
**Pull request by joelverhagen**
Related to https://github.com/NuGet/NuGetGallery/issues/5403

@kraigb, I'll let you know when I want this merged. I'd like to align it somewhat with the actual service deployment.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/api/_data/service-index.json](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-stable/docs/api/_data/service-index.json) | :white_check_mark:Succeeded | |
[docs/api/service-index.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-stable/docs/api/service-index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C12%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201802122057560348-700%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=f%2F8g9XbF9zonEZ3%2BkzU6guCjIi2DujH9IeFISto5b8E%3D&st=2018-02-12T20%3A53%3A46Z&se=2018-03-15T20%3A58%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/api/_data/service-index.json](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-stable/docs/api/_data/service-index.json) | :white_check_mark:Succeeded | |
[docs/api/service-index.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-stable/docs/api/service-index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C12%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201802122058319050-700%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sotTD8loPpGfqQJi%2FGS7e3e0NzuDobxmspKvQVn%2FUK4%3D&st=2018-02-12T20%3A54%3A41Z&se=2018-03-15T20%3A59%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joelverhagen** [comment]
@kraigb, this is ready to deploy at your earliest convenience.

**Comment by kraigb** [comment]
@joelverhagen Done

**Pull request merged**
