### PR TITLE
L132141: Escaping lt and gt characters

### PR DESCRIPTION
**Pull request by v-maudel**
Content team has reported possible source content issue. 
Description: un-escaped element <name> at the end, is causing issues in the loc versions of the files.

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[551816b](https://github.com/v-maudel/docs.microsoft.com-nuget/commits/551816b229c9ee384b6ac3b0ad37aa4527b77d4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/installing-signed-packages.md](https://github.com/v-maudel/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/installing-signed-packages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/installing-signed-packages?branch=pr-en-us-1743) | [Details](#user-content-d1f51193-d475c34b)
[docs/reference/cli-reference/cli-ref-trusted-signers.md](https://github.com/v-maudel/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-trusted-signers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers?branch=pr-en-us-1743) |

<a id="d1f51193-d475c34b"></a>
### [docs/consume-packages/installing-signed-packages.md](https://github.com/v-maudel/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/installing-signed-packages.md)
 - **Line 93**: **[Warning]** `````Invalid link: '<a href="reference/cli-reference/cli-ref-trusted-signers.md#nuget-trusted-signers-sync--name-">trusted-signers sync command</a>'. The file reference/cli-reference/cli-ref-trusted-signers.md doesn't contain a bookmark named 'nuget-trusted-signers-sync--name-'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C17%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201910172023117148-1743%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nXZBNQdf8Ysf%2BojjaMzNDWnCtKxMXwTGpDeio0%2FYxKE%3D&st=2019-10-17T20%3A19%3A22Z&se=2019-11-17T20%3A24%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[5448184](https://github.com/v-maudel/docs.microsoft.com-nuget/commits/5448184341e05db293865be13c8ad57967383fe6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/installing-signed-packages.md](https://github.com/v-maudel/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/installing-signed-packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/installing-signed-packages?branch=pr-en-us-1743) |
[docs/reference/cli-reference/cli-ref-trusted-signers.md](https://github.com/v-maudel/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-trusted-signers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers?branch=pr-en-us-1743) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C17%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201910172030203292-1743%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ryO0K5ErdabqbbQVWtkLnQqcPVVP1P6MkxQ%2FD6fymek%3D&st=2019-10-17T20%3A26%3A24Z&se=2019-11-17T20%3A31%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.

**Comment by v-maudel** [comment]
trying #sign-off

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.
please #sign-off or merge it

**Comment by v-maudel** [comment]
Hi @karann-msft, can you please help by merging this PR?
Regards.
please #sign-off or merge it
FYI @JasonCard

**Comment by JasonCard** [comment]
@Mikejo5000 Could you please help to take a look at this PR? There are couple of issues we are trying to address: 
1. The \<name\> tag in two headings are not displayed in live page. 
2. The bookmark link is broken because "#nuget-trusted-signers-sync--name-" is missing the extra "name" at end. Should be "#nuget-trusted-signers-sync--name-name" 
cc @v-maudel

**Comment by Mikejo5000** [comment]
#sign-off

**Pull request merged**
