### PR TITLE
Add column for each client's supported platform

### PR DESCRIPTION
**Pull request by loic-sharma**

### CODE REVIEW

**Review by zivkan — APPROVED** [review]

**Review by JonDouglas — APPROVED** [review]
This is great! Now that we have a separate column for platform, do you think we should drop the `.exe` extension at least for dotnet CLI? 

image

**Comment by loic-sharma** [comment]
Done! There's quite a few more tweaks I plan to do in this section, but I'll do those in subsequent pull request. Please let me know if there any other changes you'd like as part of this pull request though!

**Comment by JonDouglas** [comment]
@loic-sharma Cool, merge whenever or i'll get to it after build status & another pass.

**Comment by JonDouglas** [comment]
@loic-sharma One last check as builds are back. A quick LGTM or feel free to merge :)

**Pull request merged**
