### PR TITLE
Added NuGet Video "Create and Publish a NuGet Package with the .NET CLI"

### PR DESCRIPTION
**Pull request by chgill-MSFT**

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[b22ac1d](https://github.com/NuGet/docs.microsoft.com-nuget/commits/b22ac1dae2852358ab8211abc4360bf5f5f90236)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-6/docs/quickstart/create-and-publish-a-package-using-visual-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1886) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002102231540546-1886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z8bFx1XG5qTA6UXcD5ZYUtOnjiG0FqheaC7HbpUtkTk%3D&st=2020-02-10T22%3A27%3A30Z&se=2020-03-12T22%3A32%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zivkan** [comment]
The video fails to load on the docs preview site. I think the problem is that the link is to an HTML page that contains the video, rather than a video file itself.

**Comment by zivkan** [comment]
Looking further, you're missing `/player` at the end of the video URL

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[43b3d7c](https://github.com/NuGet/docs.microsoft.com-nuget/commits/43b3d7c6483769d9786230b7d53cce4d68cd03f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-6/docs/quickstart/create-and-publish-a-package-using-visual-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1886) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002192129024257-1886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jm%2B9snzaa9zEi1FkZU00HSgWIw%2FyBWLhzYRjSTYxGBE%3D&st=2020-02-19T21%3A24%3A44Z&se=2020-03-21T21%3A29%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
