### PR TITLE
Add NU5127, NU5129, NU5130, NU5131 docs

### PR DESCRIPTION
**Pull request by zivkan**
Fixes: NuGet/Home#8439

This PR replaces the individual PRs for each page

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[8064933](https://github.com/NuGet/docs.microsoft.com-nuget/commits/8064933d8669ea51c36a61a6d667cde9d00ff122)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5131?branch=pr-en-us-1697) |
[docs/reference/Errors-and-Warnings.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/Errors-and-Warnings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings?branch=pr-en-us-1697) |
[docs/reference/errors-and-warnings/NU5127.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/errors-and-warnings/NU5127.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5127?branch=pr-en-us-1697) |
[docs/reference/errors-and-warnings/NU5128.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/errors-and-warnings/NU5128.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128?branch=pr-en-us-1697) |
[docs/reference/errors-and-warnings/NU5129.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/errors-and-warnings/NU5129.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5129?branch=pr-en-us-1697) |
[docs/reference/errors-and-warnings/NU5130.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/errors-and-warnings/NU5130.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5130?branch=pr-en-us-1697) |
[docs/reference/errors-and-warnings/NU5131.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/zivkan-pack-validation-docs/docs/reference/errors-and-warnings/NU5131.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5131?branch=pr-en-us-1697) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C23%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201909231814153333-1697%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j3wBPo47rTywP5mbau9NjC055I8oimcRwCq51ie7wV0%3D&st=2019-09-23T18%3A10%3A28Z&se=2019-10-24T18%3A15%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@zivkan please also update - https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings

**Comment by zivkan** [comment]
@karann-msft I did. See the second file that your validation bot posted a link to :)

**Comment by karann-msft** [comment]
Ah! Thanks @zivkan!

**Pull request merged**
