### PR TITLE
Fix language identifier: cli -> dotnetcli

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[4a3efe0](https://github.com/Youssef1313/docs.microsoft.com-nuget/commits/4a3efe0fd895e402a586335b76869fd3405b1295)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/create-packages/Sign-a-Package.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Sign-a-Package.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/sign-a-package?branch=pr-en-us-1760) | [Details](#user-content-c6f8415e-fda3eab5)
[docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-visual-studio.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1760) | [Details](#user-content-77015a05-fda3eab5)
[docs/consume-packages/Packages-and-Source-Control.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/Packages-and-Source-Control.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control?branch=pr-en-us-1760) |
[docs/consume-packages/Team-Foundation-Build.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/Team-Foundation-Build.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/team-foundation-build?branch=pr-en-us-1760) |
[docs/consume-packages/configuring-nuget-behavior.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/configuring-nuget-behavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior?branch=pr-en-us-1760) |
[docs/consume-packages/includes/restore-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/includes/restore-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/includes/restore-nuget-exe-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/includes/restore-nuget-exe-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli?branch=pr-en-us-1760) |
[docs/consume-packages/install-use-packages-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/install-use-packages-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/install-use-packages-nuget-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/install-use-packages-nuget-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli?branch=pr-en-us-1760) |
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1760) |
[docs/create-packages/Creating-a-Package.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Creating-a-Package.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package?branch=pr-en-us-1760) |
[docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Symbol-Packages-snupkg.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?branch=pr-en-us-1760) |
[docs/create-packages/Symbol-Packages.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Symbol-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages?branch=pr-en-us-1760) |
[docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/creating-a-package-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli?branch=pr-en-us-1760) |
[docs/guides/Create-NET-Standard-Packages-VS2015.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/guides/Create-NET-Standard-Packages-VS2015.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-net-standard-packages-vs2015?branch=pr-en-us-1760) |
[docs/guides/Create-UWP-Packages.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/guides/Create-UWP-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-uwp-packages?branch=pr-en-us-1760) |
[docs/guides/api/query-for-all-published-packages.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/guides/api/query-for-all-published-packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages?branch=pr-en-us-1760) |
[docs/guides/create-packages-for-xamarin.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/guides/create-packages-for-xamarin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1760) |
[docs/hosting-packages/Local-Feeds.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/hosting-packages/Local-Feeds.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds?branch=pr-en-us-1760) |
[docs/nuget-org/Publish-a-package.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/nuget-org/Publish-a-package.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package?branch=pr-en-us-1760) |
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework?branch=pr-en-us-1760) |
[docs/quickstart/includes/publish-dotnet.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/includes/publish-dotnet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?branch=pr-en-us-1760) |
[docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-add.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-add?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-config.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-config.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-config?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-delete.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-delete?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-help.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-help.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-help?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-init.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-init.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-init?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-install.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-install.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-install?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-list.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-list?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-locals.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-locals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-locals?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-mirror.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-mirror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-mirror?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-pack.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-pack.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-pack?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-push.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-push.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-restore.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-restore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-setapikey.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-setapikey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-sign.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-sign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sign?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-sources.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-sources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-spec.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-spec.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-spec?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-trusted-signers.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-trusted-signers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-update.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update?branch=pr-en-us-1760) |
[docs/reference/cli-reference/cli-ref-verify.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/cli-reference/cli-ref-verify.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-verify?branch=pr-en-us-1760) |
[docs/reference/msbuild-targets.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/msbuild-targets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/msbuild-targets?branch=pr-en-us-1760) |
[docs/reference/nuspec.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/nuspec.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/nuspec?branch=pr-en-us-1760) |

<a id="c6f8415e-fda3eab5"></a>
### [docs/create-packages/Sign-a-Package.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Sign-a-Package.md)
 - **Line 17**: **[Suggestion]** `````Link 'http://aka.ms/trustcertpartners' is insecure. Links to Microsoft sites must use 'https' instead of 'http'. NOTE: This Suggestion will become a Warning on 12/20/2019.`````

<a id="77015a05-fda3eab5"></a>
### [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
 - **Line 28**: **[Suggestion]** `````Link 'https://docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts#add-a-new-individual-account' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites. NOTE: This Suggestion will become a Warning on 12/20/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911041102581052-1760%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=baMd7yW4Oku2%2F%2Bz5tLv0WGwrLiuXkh9lWsxpbWXurxY%3D&st=2019-11-04T10%3A59%3A21Z&se=2019-12-05T11%3A04%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[d20947e](https://github.com/Youssef1313/docs.microsoft.com-nuget/commits/d20947ec40288f84f601013616caba153bc938a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/creating-a-package-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911041104343606-1760%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5s0RcDYiLmE1CkG58btqJ3aUAZTmxqB00dlvbScpJBw%3D&st=2019-11-04T11%3A00%3A35Z&se=2019-12-05T11%3A05%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[40abcb9](https://github.com/Youssef1313/docs.microsoft.com-nuget/commits/40abcb9de69df84b3eb43fe7025a40a19bc65296)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/includes/restore-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/includes/restore-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/install-use-packages-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/install-use-packages-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1760) |
[docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Symbol-Packages-snupkg.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?branch=pr-en-us-1760) |
[docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/creating-a-package-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/includes/publish-dotnet.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/includes/publish-dotnet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/reference/msbuild-targets.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/msbuild-targets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/msbuild-targets?branch=pr-en-us-1760) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911041113163398-1760%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UUiCQUiL4LoML%2BgI2%2F4TG4z7i%2FKGFGcAvCKwyi0vxoQ%3D&st=2019-11-04T11%3A09%3A26Z&se=2019-12-05T11%3A14%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[a8aff0a](https://github.com/Youssef1313/docs.microsoft.com-nuget/commits/a8aff0a162db8ab5890bbfaa98fd1a3bfbb1bcb5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/Package-References-in-Project-Files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files?branch=pr-en-us-1760) |
[docs/consume-packages/includes/restore-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/includes/restore-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/install-use-packages-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/install-use-packages-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli?branch=pr-en-us-1760) |
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1760) |
[docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/Symbol-Packages-snupkg.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?branch=pr-en-us-1760) |
[docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/create-packages/creating-a-package-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/includes/publish-dotnet.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/includes/publish-dotnet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli?branch=pr-en-us-1760) |
[docs/reference/errors-and-warnings/NU5030.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/errors-and-warnings/NU5030.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5030?branch=pr-en-us-1760) |
[docs/reference/errors-and-warnings/NU5032.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/errors-and-warnings/NU5032.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5032?branch=pr-en-us-1760) |
[docs/reference/errors-and-warnings/NU5037.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/errors-and-warnings/NU5037.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5037?branch=pr-en-us-1760) |
[docs/reference/msbuild-targets.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/reference/msbuild-targets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/msbuild-targets?branch=pr-en-us-1760) |
[docs/release-notes/NuGet-1.3.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/release-notes/NuGet-1.3.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-1.3?branch=pr-en-us-1760) |
[docs/release-notes/NuGet-2.5.md](https://github.com/Youssef1313/docs.microsoft.com-nuget/blob/patch-1/docs/release-notes/NuGet-2.5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-2.5?branch=pr-en-us-1760) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911041121020262-1760%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=91CJr2KcFDVnxUnmPgGiXcl40KZVY6HgdAQ0EdQZJxo%3D&st=2019-11-04T11%3A17%3A13Z&se=2019-12-05T11%3A22%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@Youssef1313 please tag me when you want me to take a look at this PR. Thanks for your contributions to make NuGet docs better!

**Comment by Youssef1313** [comment]
@karann-msft, this was ready for review since the last commit but I've forgotten to remove the "Work in progress" from it 😄
You can review it.

**Comment by karann-msft** [comment]
@Youssef1313 - where did you see this convention for changing `cli` to `.NET Core cli`? @Mikejo5000 - can you chime in if this is the right thing?

**Comment by Youssef1313** [comment]
@karann-msft, In past, dotnetcli wasn't supported. but now it's supported and used in dotnet docs. Live example is in [dotnet new docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore22). You'd see that it gets proper highlighting.

**Comment by Mikejo5000** [comment]
@karann-msft Looks like the right thing for .NET Core CLI commands now.

**Pull request merged**
