### PR TITLE
Fixes #1826

### LINKED ISSUE #1826: FAQ - nuget.org - username change improvement
How do I change my NuGet.org account username? part of the FAQ should call out that trust polciies might be broker for customers. 

https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#how-do-i-change-my-nugetorg-account-username

//cc @loic-sharma

### PR DESCRIPTION
**Pull request by karann-msft**
Fixes #1826

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[a686735](https://github.com/NuGet/docs.microsoft.com-nuget/commits/a68673522815a08dba6cb3f0f689189bb01d30ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/nuget-org-faq.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-1826/docs/nuget-org/nuget-org-faq.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq?branch=pr-en-us-1827) | [Details](#user-content-82ebb076-0180a1e7)

<a id="82ebb076-0180a1e7"></a>
### [docs/nuget-org/nuget-org-faq.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-1826/docs/nuget-org/nuget-org-faq.md)
 - **Line 240**: **[Warning]** `````Invalid file link: '../consume-packages/installing-signed-packages'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202001061716575658-1827%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3PioetY%2BnPAEYcwVms7K8ZkrUTUoUXLnQ0ap1wHvMYY%3D&st=2020-01-06T17%3A12%3A30Z&se=2020-02-06T17%3A17%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
ignore the build warning. the link works fine.

**Comment by DuncanmaMSFT** [comment]
The rest of the links in that file, to other docs, end with .md (the file extension), which is the right syntax for internal links

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[87bee5c](https://github.com/NuGet/docs.microsoft.com-nuget/commits/87bee5c30e9080ab3c494936894a1f12e64df4b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/nuget-org-faq.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/karann-msft-1826/docs/nuget-org/nuget-org-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq?branch=pr-en-us-1827) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C6%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202001061729477091-1827%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rGf2E14pw%2Bt4bSDv%2B6jGLKc14Y8dAEaQk3tbgfa9JvE%3D&st=2020-01-06T17%3A25%3A21Z&se=2020-02-06T17%3A30%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
