### PR TITLE
Added Cloudsmith to services that support NuGet

### PR DESCRIPTION
**Pull request by lskillen**
Hello!

This adds [Cloudsmith](https://cloudsmith.io) to the supported services for NuGet hosting.

Thank  you. :-)

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[1b92cf1](https://github.com/lskillen/docs.microsoft.com-nuget/commits/1b92cf17aaa3e0b4ba7aaf1599cbaf598119715c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/hosting-packages/Overview.md](https://github.com/lskillen/docs.microsoft.com-nuget/blob/patch-1/docs/hosting-packages/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/hosting-packages/overview?branch=pr-en-us-1657) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C3%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201909032158505436-1657%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NFUh6pS9W9ZrOtvClZNM1To%2FJKMTzEF%2B8cltu%2Bkha3I%3D&st=2019-09-03T21%3A54%3A53Z&se=2019-10-04T21%3A59%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[6312ee9](https://github.com/lskillen/docs.microsoft.com-nuget/commits/6312ee9716deeff8fb396c18853d7dec39164a34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/hosting-packages/Overview.md](https://github.com/lskillen/docs.microsoft.com-nuget/blob/patch-1/docs/hosting-packages/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/hosting-packages/overview?branch=pr-en-us-1657) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C3%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201909032205365955-1657%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qUuqZ3oxU%2B4Sel81DnPcYxGbnbs9sD3iHNxMzvxClrM%3D&st=2019-09-03T22%3A01%3A38Z&se=2019-10-04T22%3A06%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lskillen** [comment]
@karann-msft Let us know if changes or anything else is required for this.

A happy aside is that we were told by @joelverhagen that [we're the first to implement support for PackageDetailsUriTemplate](https://twitter.com/joelverhagen/status/1170010543878369280) after nuget.org, which is quite nice. :-)

Also posted a screenshot with it. Keep up the great work!

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[6071a42](https://github.com/lskillen/docs.microsoft.com-nuget/commits/6071a429e95032e54923c64c1e425d6c87d9e25a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/hosting-packages/Overview.md](https://github.com/lskillen/docs.microsoft.com-nuget/blob/patch-1/docs/hosting-packages/Overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/hosting-packages/overview?branch=pr-en-us-1657) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C9%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201909091856143636-1657%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7yA1fWO0AwJ1CZYerdQPgv5A%2BMKzk1JaefvCUTWW1qY%3D&st=2019-09-09T18%3A52%3A11Z&se=2019-10-10T18%3A57%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@lskillen - that's awesome!!! And thank you for the kind words. Merging the PR, with a small tweak.

**Comment by lskillen** [comment]
@karann-msft Much appreciated, thank you as well. :)

**Pull request merged**
