### PR TITLE
Update NuGet-4.5-RTM.md

### PR DESCRIPTION
**Pull request by anangaur**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Release-Notes/NuGet-4.5-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-pass2/docs/Release-Notes/NuGet-4.5-RTM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C7%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201712071844209321-594%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4CuG21%2FdJ5TUGhPWwGbthEFnAq3VDa0YJ9WIPXCZ%2BdQ%3D&st=2017-12-07T18%3A40%3A54Z&se=2018-01-07T18%3A45%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Release-Notes/NuGet-4.5-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-pass2/docs/Release-Notes/NuGet-4.5-RTM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C7%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201712071849057259-594%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TpXCdu0UTlffWLPxsh5ygceu9Qlk6ByYoZ5PJcd7WMs%3D&st=2017-12-07T18%3A44%3A49Z&se=2018-01-07T18%3A49%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anangaur** [comment]
@karann-msft Can you review why the ToC doesn't show the release notes for 4.5?

**Comment by karann-msft** [comment]
the ToC file needs to be updated https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/TOC.md

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Release-Notes/NuGet-4.5-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-pass2/docs/Release-Notes/NuGet-4.5-RTM.md) | :white_check_mark:Succeeded | |
[docs/TOC.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-pass2/docs/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C7%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201712071858085288-594%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=r9LPm%2F5ZT3kO%2BPR3YfzhOO3DBqhARWlLn5KFZ0cOjH8%3D&st=2017-12-07T18%3A54%3A31Z&se=2018-01-07T18%3A59%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
we should merge to master and from master to live.

**Pull request merged**
