### PR TITLE
Update Publish-a-package.md - VSTS doc

### PR DESCRIPTION
**Pull request by anangaur**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-vsts-latest-nuget-client/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C20%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710202237347502-521%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dA0TP1Tr5YOKRbq%2FSfki%2F0i4rkP1cN8pFKeLa19qeR4%3D&st=2017-10-20T22%3A33%3A17Z&se=2017-11-20T22%3A38%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-vsts-latest-nuget-client/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C20%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710202245486981-521%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=o5o2h5D5DCLyewVSiI99b0zBLHOK7q7mkraOho0Capw%3D&st=2017-10-20T22%3A41%3A28Z&se=2017-11-20T22%3A46%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Create-Packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-vsts-latest-nuget-client/docs/Create-Packages/Publish-a-package.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710241618285149-521%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gmptJKawG7mHfa%2FoMeevaZHT1gP5gwCK3EBvfauihAw%3D&st=2017-10-24T16%3A14%3A10Z&se=2017-11-24T16%3A19%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@anangaur FYI, always check your changes on the staging server, e.g. https://review.docs.microsoft.com/en-us/nuget/create-packages/publish-a-package?branch=anangaur-vsts-latest-nuget-client, as in this case the indentation was incorrect which resulted in incorrect rendering. I've fixed that, but wanted to make sure you knew.

**Pull request merged**
