### PR TITLE
Freshness Pass User Story: 173521

### PR DESCRIPTION
**Pull request by GitHubber17**
This PR contains freshness updates to 2 articles and a few other files to support the main changes.

- **[Install NuGet client tools](https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools)** + [include file](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/includes/install-cli.md)
- **[How to reinstall and update packages](https://learn.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages)**

See User story: [173521](https://dev.azure.com/msft-skilling/Content/_workitems/edit/173521)

### CODE REVIEW

**Comment by GitHubber17** [comment]
Hi @JonDouglas @nkolev92 - This freshness pass is ready for your review. I updated two articles plus related files:

- **Install NuGet client tools** [review changes](https://review.learn.microsoft.com/en-us/nuget/install-nuget-client-tools?branch=pr-en-us-3172&tabs=windows)

- **Reinstall and update NuGet packages in Visual Studio** [review changes](https://review.learn.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages?branch=pr-en-us-3172)

Thanks

**Comment by JonDouglas** [comment]
@GitHubber17 Wow, thank you so much for this! Can I ask for a few minor changes just due to our product changes in the last couple years?

1. Any dotnet SDK or Visual Studio/Visual Studio Code scenario should be first in any list. Everything else should be pushed down.

https://review.learn.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages?branch=pr-en-us-3172#implementation-options -> Bring up "Package Manager UI" to the top of implementation options.

https://review.learn.microsoft.com/en-us/nuget/install-nuget-client-tools?branch=pr-en-us-3172&tabs=macos -> Change "dotnet.exe" to "dotnet SDK" everywhere and [remove Visual Studio for Mac as it is being sunsetted](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022) or a small note/link to this page to let users know it will be retired for now.

Consider removing entirely https://review.learn.microsoft.com/en-us/nuget/install-nuget-client-tools?branch=pr-en-us-3172&tabs=windows#install-on-visual-studio-2015-and-earlier and update https://review.learn.microsoft.com/en-us/nuget/install-nuget-client-tools?branch=pr-en-us-3172&tabs=windows#install-on-visual-studio-2017-and-later to be reflective of 2022+

**Comment by GitHubber17** [comment]
@JonDouglas -- Hi Jon, Thanks for your feedback! I made the following updates:

- Added Note about VS for Mac retirement
- Replaced "dotnet.exe" with "dotnet SDK"
- Removed most installation details for earlier VS versions
- Few other changes, as you requested

I'm not exactly clear on when to use "dotnet SDK," "dotnet CLI," or "dotnet SDK CLI." If any particular instance is wrong, would you add an inline review comment to the file, so I know which instances to fix?

Here are the two main files, plus another with updates links for the dotnet SDK:

- https://review.learn.microsoft.com/nuget/install-nuget-client-tools?branch=pr-en-us-3172
- https://review.learn.microsoft.com/nuget/consume-packages/reinstalling-and-updating-packages?branch=pr-en-us-3172
- https://review.learn.microsoft.com/nuget/resources/check-project-format?branch=pr-en-us-3172 (dotnet SDK links)

Thank you :-)

**Comment by JonDouglas** [comment]
@GitHubber17 The `dotnet SDK` is the software development kit that includes nuget experiences. A developer uses the included `CLI`(command line interface) to interact with the SDK. When we are referring to installing tools, we refer to installing the `dotnet SDK` or `.NET SDK`.

Much of our existing terminology is incorrectly referencing `dotnet.exe` and `dotnet CLI`. While `dotnet CLI` is more correct, we really mean `dotnet SDK` and using CLI within it.

This is looking great, thank you for addressing everything!

**Review by JonDouglas — APPROVED** [review]
LGTM, thank you kindly for the contribution! We really appreciate it!

**Comment by GitHubber17** [comment]
#sign-off

**Review by nkolev92 — APPROVED** [review]

**Comment by GitHubber17** [comment]
@JonDouglas @nkolev92 -- Will someone on your team merge PR into the repo?

**Pull request merged**
