### PR TITLE
Added NuGet Video "Create and Publish a NuGet Package with the .NET CLI"

### PR DESCRIPTION
**Pull request by chgill-MSFT**
In the preview it doesn't show the video, but it seems to appear fine when published. This is the exact type of embedding used in other docs with videos such as:
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/includes/xamarin-show-essentials.md

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[ee958b9](https://github.com/NuGet/docs.microsoft.com-nuget/commits/ee958b97dbf3770e6894e36cc9ffbb38f8d8b4db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-5/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1885) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002102203169631-1885%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EsTSvaye%2FE4nkTJNxIMQkqs3GmUrptT7SABCwieT9ok%3D&st=2020-02-10T21%3A58%3A51Z&se=2020-03-12T22%3A03%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zivkan** [comment]
How do you know the embedded video will work when published?  The URL is to a web page, not a video file, so it makes sense to me that the embedded video doesn't render. The link you provided to as an example doesn't contain an embedded video, only links to channel9 and youtube.

**Comment by zivkan** [comment]
Looking further, you're missing `/player` at the end of the video URL. Additionally, next time please create 1 PR with all the changes. It reduces review workload.

**Comment by karann-msft** [comment]
@chgill-MSFT - the video does not render https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1885
image

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[4d9e73d](https://github.com/NuGet/docs.microsoft.com-nuget/commits/4d9e73d768ef31899cdf9e175e318ea0fe6f6e0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-5/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1885) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002192124001000-1885%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xow5iyidRvf3YBd0lrwlDhJSKs8ousx%2BJIDLDBEf6F4%3D&st=2020-02-19T21%3A19%3A39Z&se=2020-03-21T21%3A24%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[5c64d90](https://github.com/NuGet/docs.microsoft.com-nuget/commits/5c64d90b695e98c7af7aa0517846380ab8e044f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/chgill-MSFT-patch-5/docs/quickstart/create-and-publish-a-package-using-the-dotnet-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli?branch=pr-en-us-1885) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002192200059587-1885%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VcWG8l5ntzIi1mmqaqlNp4JTEiijh%2Bu0OGnheIRvfk4%3D&st=2020-02-19T21%3A55%3A46Z&se=2020-03-21T22%3A00%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
