### PR TITLE
Fixes to the suggestions on the repo

### PR DESCRIPTION
**Pull request by Mikejo5000**

### CODE REVIEW

**Comment by Mikejo5000** [comment]
@JonDouglas Jon, here are fixes to GitHub suggestions to clean up our build validation reports.

**Comment by Mikejo5000** [comment]
@anangaur Anand, with Jon out, can you merge these fixes to warnings? Thanks!

**Comment by anangaur** [comment]
Done!

**Comment by Mikejo5000** [comment]
Thanks, Anand!

**Pull request merged**
