### PR TITLE
Issue fix

### PR DESCRIPTION
**Pull request by Mikejo5000**

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[7956c92](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1583/commits/7956c92e2385562e03dbe84138de64397cfa0ee3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-updates2/docs/consume-packages/Finding-and-Choosing-Packages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1583) | [Details](#user-content-1e91afe3-a52ca173)

<a id="1e91afe3-a52ca173"></a>
### [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-updates2/docs/consume-packages/Finding-and-Choosing-Packages.md)
 - **Line 115**: **[Warning]** `````Illegal link: `<a href="reference/msbuild-targets.md#packing-a-license-expression-or-a-license-file.">Packing a license expression or a license file</a>` -- missing bookmark. The file reference/msbuild-targets.md doesn't contain a bookmark named packing-a-license-expression-or-a-license-file..`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C31%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907312106294873-1583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ras7GITwcOj2%2FHqwmlLJOh0iVk6KE4%2BvogQdlQhIrQ8%3D&st=2019-07-31T21%3A02%3A36Z&se=2019-08-31T21%3A07%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Mikejo5000** [comment]
Fix to NuGet/Home/8389

**Comment by Mikejo5000** [comment]
NuGet/8389

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[12cfe28](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1583/commits/12cfe280a83ab9b703a0da8036e25edbcaa1665d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-updates2/docs/consume-packages/Finding-and-Choosing-Packages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1583) | [Details](#user-content-1e91afe3-a3c409eb)

<a id="1e91afe3-a3c409eb"></a>
### [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-updates2/docs/consume-packages/Finding-and-Choosing-Packages.md)
 - **Line 115**: **[Warning]** `````Invalid file link:(~/reference/msbuild-targets#packing-a-license-expression-or-a-license-file.).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C31%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907312116362086-1583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m3lqG9IHqBV%2Bacy9a9xexyn2c0ZsvdQt%2FwyUjhJor3Q%3D&st=2019-07-31T21%3A12%3A32Z&se=2019-08-31T21%3A17%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[29b5a38](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1583/commits/29b5a38061e5eaccd25912978e36276d5a71ec3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/mikejo-updates2/docs/consume-packages/Finding-and-Choosing-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1583) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C31%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907312122278631-1583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o93GVUyAO5yX4V%2FnPCEefNeiFqTNXqVJGk2COpE8oRA%3D&st=2019-07-31T21%3A18%3A24Z&se=2019-08-31T21%3A23%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
