### PR TITLE
Add documentation for RestoreUseSkipNonexistentTargets

### PR DESCRIPTION
**Pull request by pascalberger**
Add documentation for `RestoreUseSkipNonexistentTargets` environment variable.

Fixes https://github.com/NuGet/Home/issues/7415

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/tools/cli-ref-environment-variables.md](https://github.com/pascalberger/docs.microsoft.com-nuget/blob/patch-1/docs/tools/cli-ref-environment-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables?branch=pr-en-us-1102) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201810190706413650-1102%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=c%2BNnwF%2F17J0KQifrdoO%2FKpYhevHrd4DN8mMZI8H%2BkDg%3D&st=2018-10-19T07%3A02%3A50Z&se=2018-11-19T07%3A07%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@rrelyea @nkolev92 can you please review this? Thanks!

**Comment by pascalberger** [comment]
@karann-msft @rrelyea @nkolev92 Any chance to get this merged?

**Comment by nkolev92** [comment]
The issue that I have with calling it out like this is that it's not truly a NuGet.exe specific environment variable. 

It's an MSBuild property in the NuGet.targets, and MSBuild treats env vars as properties. 

Namely, RestoreUseSkipNonexistentTargets is just one of many. 

I feel like we need to call out the above behavior and provide RestoreUseSkipNonexistentTargets as an example. 

I will try to come up with a proposal soon.

**Comment by nkolev92** [comment]
Apologies for the delay, my PR is https://github.com/NuGet/docs.microsoft.com-nuget/pull/1395

**Comment by nkolev92** [comment]
The other PR is merged

**Pull request closed without merging**
