### PR TITLE
Updated cross-platform NuGet docs for VS 2017/19

### PR DESCRIPTION
**Pull request by michizhou**
Updated documentation about how to create NuGet packages for cross-platform Xamarin plugin templates to provide more accurate guidance for users of Visual Studio 2017 and 2019. Pending approval from reviewers with the possibility of further changes to be added.

Fixes xamarin/Xamarin.Forms#8070

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[9102637](https://github.com/michizhou/docs.microsoft.com-nuget/commits/9102637ede77582db2dc59bb97e8ce5036d1da4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/guides/create-packages-for-xamarin.md](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/create-packages-for-xamarin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part1.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part2.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C30%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201910300922066391-1758%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zPf81GkpWLhIqAYLDGK%2Ft%2Ff7vhbk34IYUEQDPpLjUUg%3D&st=2019-10-30T09%3A18%3A12Z&se=2019-11-30T09%3A23%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[e6eea27](https://github.com/michizhou/docs.microsoft.com-nuget/commits/e6eea27d75378cdfb96f215e349a0dd28c3558cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/guides/create-packages-for-xamarin.md](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/create-packages-for-xamarin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part1.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part2.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C30%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201910300925488842-1758%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tDWoWyB3I1PtCJ4fF0uCYaSUQmDN2oZhOJjIzvCebjY%3D&st=2019-10-30T09%3A21%3A42Z&se=2019-11-30T09%3A26%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@pauldipierto can u help review this PR?

**Comment by karann-msft** [comment]
@michizhou - can you please action @asb3993 feedback to get this PR merged. Thanks.

**Comment by michizhou** [comment]
@asb3993 What exactly do you mean by TOC? If you could leave a comment in my changes indicating what item you are referring to, I'd greatly appreciate it. Also for ms.date, do you just want me to update it to the current date, or did you have a recent date in particular? Please let me know.

**Comment by karann-msft** [comment]
@michizhou - current date works! Thanks!

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[47d23d5](https://github.com/michizhou/docs.microsoft.com-nuget/commits/47d23d51fe7b271ec07649b65993e539a87cdb5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.md](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/create-packages-for-xamarin.md](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/create-packages-for-xamarin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part1.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |
[docs/guides/media/CrossPlatform-NewProject19-Part2.png](https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/media/CrossPlatform-NewProject19-Part2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin?branch=pr-en-us-1758) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911052146106162-1758%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V1iui8e%2FSVhvMhxnCJqNspvZcFBAnGx6kWEbnz1PZvc%3D&st=2019-11-05T21%3A42%3A26Z&se=2019-12-06T21%3A47%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
