### PR TITLE
Document the new plugin protocol + new cross platform authentication plugin

### PR DESCRIPTION
**Pull request by nkolev92**
Follow up as https://github.com/NuGet/docs.microsoft.com-nuget/pull/951 was merged by accident. 

There are some TBD left, as our docs should link back to the VSTS docs. 

**DO NOT MERGE**

//cc @rrelyea @dtivel @NuGet/nuget-client @anangaur

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-plugins?branch=pr-en-us-1006) |
[docs/tools/cli-ref-locals.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/tools/cli-ref-locals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/cli-ref-locals?branch=pr-en-us-1006) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C8%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201808081934421937-1006%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BxIg5RhHuMqTz9kER7DNdnsMJezJpRe6k%2BgLjzfQ6TM%3D&st=2018-08-08T19%3A30%3A44Z&se=2018-09-08T19%3A35%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-plugins?branch=pr-en-us-1006) |
[docs/tools/cli-ref-locals.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/tools/cli-ref-locals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/cli-ref-locals?branch=pr-en-us-1006) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201808231847054251-1006%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TnbuUjkudRWz0Mg%2F1rQBq7SOjbKU6e7Vl705P%2FpjzO0%3D&st=2018-08-23T18%3A43%3A11Z&se=2018-09-23T18%3A48%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/consume-packages/managing-the-global-packages-and-cache-folders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Credential-Providers-for-Visual-Studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin?branch=pr-en-us-1006) |
[docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/reference/extensibility/NuGet-Cross-Platform-Plugins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-plugins?branch=pr-en-us-1006) |
[docs/tools/cli-ref-locals.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-plugins/docs/tools/cli-ref-locals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/cli-ref-locals?branch=pr-en-us-1006) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201808231848465759-1006%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ScTpD3uYMsAhM4EX0cHI%2BynMrPoe%2FEBsSzLMzcVFRX8%3D&st=2018-08-23T18%3A44%3A50Z&se=2018-09-23T18%3A49%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nkolev92** [comment]
@anangaur Addressed the first 3 comments. 
As discussed offline, let's merge this in, and then you can your refactoring on top of everything.

**Pull request merged**
