### PR TITLE
Fixes #469

### LINKED ISSUE #469: "Restore vs. install" and "Dependency installs" seem to be missing after Nuget.org's facelift.
*Restore vs. install* and *Dependency installs* seem to be missing after Nuget.org's [facelift](https://blog.nuget.org/20170718/NuGet-Gallery-Gets-A-Facelift.html).

> - *Restore vs. new install*: on the same package statistics page, clear the **Version** checkbox and select **Operation** to see a chart of package restores vs. new installs (below).
> 
>     Chart of operations for a NuGet package on nuget.org package statistics
> 
> - *Dependency installs*: the same **Operation** chart above has an "Install-Dependency" bar that indicates how many other NuGet packages have taken a dependency on this one. This is an even stronger indication that other developers find the package reliable.

If these features were removed from the site we should probably remove the references to them as well. If the features weren't removed, where can they be found?

### PR DESCRIPTION
**Pull request by alfredmyers**
Fixes #469

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Consume-Packages/Finding-and-Choosing-Packages.md](https://github.com/alfredmyers/docs.microsoft.com-nuget/blob/patch-5/docs/Consume-Packages/Finding-and-Choosing-Packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C17%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201709172032116374-470%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e189EWUAjd5MtCPcM61eLT2fNoHf0PPrn2H5uNqqVJ4%3D&st=2017-09-17T20%3A27%3A49Z&se=2017-09-18T20%3A37%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@karann-msft can you review?

**Comment by kraigb** [comment]
Verified with changes to nuget.org; thanks for the edits.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 357**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;tmp_pack_QqZNTa&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201710022331271783-470%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jls4sN7OHbjD2v85UUDZVxToQaPZsqYa%2FaW4IIb1xYk%3D&st=2017-10-02T23%3A36%3A49Z&se=2017-10-03T23%3A46%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
Thanks; I verified the changes with the current nuget.org UI. I appreciate you taking the time to make the edits!

**Pull request merged**
