### PR TITLE
CC74600: Unnecessarily nested lists

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @karann-msft,
This proposed file change comes from https://github.com/NuGet/docs.microsoft.com-nuget.es-es/pull/4 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/v-makoud/docs.microsoft.com-nuget/blob/patch-1/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/index?branch=pr-en-us-1091) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C12%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201810120820469397-1091%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A8SjfbmYYE6%2BKxfT8JtSGLA0CLcTOHZ%2ByBwtTLBm9r4%3D&st=2018-10-12T08%3A16%3A54Z&se=2018-11-12T08%3A21%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@v-makoud I am not sure I understand the impact. What are we trying to change here? Is it this page?

**Comment by v-maudel** [comment]
Hi @karann-msft , 
Contributor claims that there were unnecessarily nested lists, making the file look bad. 
As this change came from a localized PR wee need to report it but please, just take a look at the changes and let us know if you agreed. 

Regards.

**Comment by v-makoud** [comment]
Hi @karann-msft ,
Contributor claims that there were unnecessarily nested lists, making the file look bad.
As this change came from a localized PR wee need to report it but please, just take a look at the changes and let us know if you agreed.

Regards.

**Comment by v-makoud** [comment]
Hi @karann-msft ,
Contributor claims that there were unnecessarily nested lists, making the file look bad.
As this change came from a localized PR wee need to report it but please, just take a look at the changes and let us know if you agreed.

Regards.

**Comment by zivkan** [comment]
I copied the change to a new branch `zivkan-test`, so that it can be viewed in the docs review tool. The index page with the change looks exactly the same as without the change.  Therefore the only benefit is for people who view source, but it doesn't appear to cause any problems.

**Comment by karann-msft** [comment]
Thanks @v-makoud @v-maudel  @zivkan

**Comment by zivkan** [comment]
In case anyone looks at this PR, I made a mistake in my `zivkan-test` branch and didn't actually merge the change. This PR in fact broke the layout of the index change, so it has been reverted.

**Pull request merged**
