### PR TITLE
Add note for namespaces required for nuget.protocol samples

### PR DESCRIPTION
**Pull request by zivkan**
Fixes: https://github.com/nuget/home/issues/10023

### CODE REVIEW

**Comment by JonDouglas** [comment]
@zivkan Note is fine & can merge as is, but should we just add the usings to the examples?

**Comment by zivkan** [comment]
The samples on this page only show the method body, not the using statements at the top of the file. Otherwise the appropriate usings would already be visible. If we change the snippet to include the usings, then this page will get a lot longer.

What do you think is best?

**Comment by JonDouglas** [comment]
Here's a few options:

1. New code snippet with all the usings
2. Usings in each snippet
3. Merge as is

My only concern with 3) is that there's other using statements like NuGet.Common & others to run the code.

**Comment by zivkan** [comment]
@NuGet/nuget-client @loic-sharma  does anyone else have an opinion in which way we should go?

Do we make all our samples longer with all the using statements?  Merge my current note as-is?

For all the other usings, Intelliesense makes it very easy to find the correct using and add it. But extension methods aren't as easy to find with Intellisense, and changing the namespace would be a breaking change, hence why we haven't changed the NuGet SDK, as mentioned in the linked issue.

**Comment by donnie-msft** [comment]
I say go with 3, as this just appears to be an unclear sample and that would help.

The discussion seems more about greatly improving all of our code samples (maybe we could use embedded code snippets... whatever the try.net plugin is called). In that case, you'd get option 2, plus a richer experience overall.

**Review by JonDouglas — APPROVED** [review]
Approving to consider merge. There's nothing blocking, just considerations.

**Comment by dominoFire** [comment]
I prefer samples you can copy-paste directly on your code. It could be:

- `using` statements added as comments in the actual snippet
- Complete working code snippet
- Link to nuget/samples repo with a working sample

**Review by dominoFire — APPROVED** [review]

**Review by donnie-msft — APPROVED** [review]

**Comment by zivkan** [comment]
So I had a bit of a look around to see how it's done elsewhere.

The [docs on XmlReader](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlreader?view=net-5.0) has a method that can be copy/pasted, but it doesn't have using statements, and it's not a complete example (needs a little extra code to call the method).

However, the [docs on the Version class](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=net-5.0) have samples which have a `static void Main`, and have using statements, so could be copied into a `.cs` file and compiled & run as is.

The [docs on LINQ overview](https://docs.microsoft.com/en-us/dotnet/standard/linq/) don't have a single `using` statement example.

The [docs on using System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0) start off with code snippets. Before using the APIs in a snippet, they have a snippet with the using statements, then a bunch of code snippets without using statements. However, at the end of the page they have two complete sample programs, including using statements, a `static void Main`, and comments showing expected output.

So, it seems to be all over the place. In general, if people copy paste our samples, Intellisense should give suggestions for which namespaces to add using statements for. For the specific API in the issue this PR fixes, it doesn't work very well if you type out the sample, rather than copy, paste, & use intellisense to add usings.

There's certainly scope for us to improve NuGet SDK samples, but our primary business is tooling, not the NuGet SDK, so I'm going to merge this as is.  Maybe if we do another docs day I'll try to remember to improve our API docs further.

**Pull request merged**
