### PR TITLE
metadata fixes

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[b71901a](https://github.com/mairaw/docs.microsoft.com-nuget/pull/1501/commits/b71901a101508a293fc5d45db46728a17a649f41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/package-installation-process.md](https://github.com/mairaw/docs.microsoft.com-nuget/blob/metadata2/docs/concepts/package-installation-process.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/concepts/package-installation-process?branch=pr-en-us-1501) |
[docs/release-notes/NuGet-5.1-RTM.md](https://github.com/mairaw/docs.microsoft.com-nuget/blob/metadata2/docs/release-notes/NuGet-5.1-RTM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-5.1-rtm?branch=pr-en-us-1501) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C3%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201907030329113747-1501%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ckWI1hQjimqju4CQA3kj7ua4tAW4ftA8KnnAd3WlsyQ%3D&st=2019-07-03T03%3A25%3A07Z&se=2019-08-03T03%3A30%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mairaw** [comment]
The release notes are also not linked to the TOC. Not sure if by design or not.

**Comment by karann-msft** [comment]
The omission from ToC is definitely not by design. @mairaw - can you please make the change in your branch as part of your PR and I'll merge it. Thanks for catching this!

**Comment by karann-msft** [comment]
thanks @mairaw !

**Pull request merged**
