### PR TITLE
remove the broken links which go to codeplex

### PR DESCRIPTION
**Pull request by huypub**

### CODE REVIEW

**Comment by Mikejo5000** [comment]
@zivkan @JonDouglas Closed the Insecure Link fix PR in favor of this PR, which removes the broken links that go to the decommissioned codeplex site, but retains the link text.

**Comment by j-martens** [comment]
@zivkan @JonDouglas  - can you please review and approve this PR? Thank you!

**Comment by JonDouglas** [comment]
Can I get some context as to why these links are being removed? Can we just update them from http to https to appease the tooling so we can hold onto the link for historical reasons? i.e. internet archive searching?

**Comment by Mikejo5000** [comment]
@JonDouglas The main issue is that if we just switch to https we still have broken links that give customers 404s (aside from tooling suggestions). An alternative might be to put the entire link into code style instead of a markdown link. Would that be preferred to the solution in this PR?

**Comment by nkolev92** [comment]
Given that these changes are in the release notes only, the value is primarily historical. 

I like changing the entire link into code style.

**Comment by JonDouglas** [comment]
Let's just move them to code style links then. I find it a bit unnecessary to remove historical links in the first place, even if they 404. Release notes need to be left alone as much as possible.

**Comment by huypub** [comment]
As suggested, I will use the code style for the broken links instead of removing them. So I will close this PR.

**Pull request closed without merging**
