### PR TITLE
update path to Package-restore-troubleshooting.md

### PR DESCRIPTION
**Pull request by trivalik**
fix dead link to troubleshooting

### CODE REVIEW

**Comment by JonDouglas** [comment]
@trivalik Thank you for the contribution! The links are not case sensitive so this should work today. At least as I checked this out here vs. your contribution.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#troubleshooting

Does the link not work for you on your end?

**Comment by trivalik** [comment]
Your link is working but if you are here in github, and click the last link on https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md you come to https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/package-restore-troubleshooting.md which is not existing.

**Comment by JonDouglas** [comment]
@trivalik Great catch! Let's add that in then for easier GitHub navigation. Thanks again for the contribution!

**Review by JonDouglas — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
