### PR TITLE
Update nuspec.md

### PR DESCRIPTION
**Pull request by anangaur**
Based on a customer support request, making this clearer and hosting logo on github looks like a general scenario.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Schema/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-patch-4/docs/Schema/nuspec.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C4%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201706040559111075-363%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Schema/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-patch-4/docs/Schema/nuspec.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201706052350212346-363%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Schema/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-patch-4/docs/Schema/nuspec.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201706052350565247-363%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
I editing a few words, but looks good otherwise.

**Pull request merged**
