### PR TITLE
change nuspec.xsd example

### PR DESCRIPTION
**Pull request by heng-liu**
Fix https://github.com/NuGet/docs.microsoft.com-nuget/issues/1749
Changed "http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd" to an existing xsd

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[1fc6663](https://github.com/NuGet/docs.microsoft.com-nuget/commits/1fc66633a6ac3b020f23dcd1834c3519cbe747d6)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[1fc6663](https://github.com/NuGet/docs.microsoft.com-nuget/commits/1fc66633a6ac3b020f23dcd1834c3519cbe747d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/dev-hengliu-change-example-nuspec.xsd/docs/reference/nuspec.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/nuspec?branch=pr-en-us-1915) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C28%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002281745503494-1915%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CuHNViga9ZrkFaH9D9iHB1TmXn02npB6jYlHIQ7DQss%3D&st=2020-02-28T17%3A41%3A32Z&se=2020-03-30T17%3A46%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
@heng-liu - what issue does this fix?

**Comment by nkolev92** [comment]
I don't think any of the xsds exist.

**Comment by zkat** [comment]
Should they exist?

**Comment by zkat** [comment]
@karann-msft https://github.com/NuGet/docs.microsoft.com-nuget/issues/1749 -- it's in the OP

**Comment by heng-liu** [comment]
Those xsds are not used for now. But we're checking if it exists [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L65-L81) 
If it's not in VersionToSchemaMappings, we will throw an exception.
So I suggest not to put an xsd which is not in VersionToSchemaMappings as an example in doc.

**Comment by heng-liu** [comment]
> Could you please change this one as well?

Thanks for reviewing! :)May I know which one are you referring to? Looks like the link is not correct?

**Comment by zkat** [comment]
@heng-liu line 44 in the same file.

**Comment by heng-liu** [comment]
> @heng-liu line 44 in the same file.
Sorry! I forgot to answer your first question...
If the .xsd file is one of the SchemaVersion in [VersionToSchemaMappings](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23-L50) it won't throw exception.
The .xsd in line 44 is [here,](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23) so it should be a good example :)

**Comment by heng-liu** [comment]
> @heng-liu line 44 in the same file.

Sorry! I forgot to answer your first question...
If the .xsd file is one of the SchemaVersion in VersionToSchemaMappings it won't throw exception.
The .xsd in line 44 is here, so it should be a good example :)

**Comment by zkat** [comment]
oh ok! Looks good to me, then. :~)

**Comment by heng-liu** [comment]
> @heng-liu line 44 in the same file.

Sorry! I forgot to answer your first question...
If the .xsd file is one of the SchemaVersion in [VersionToSchemaMappings ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23-L59), it won't throw exception.
The .xsd in line 44 is [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23), so it should be a good :)
Or do you mean to keep it the same everywhere?

**Comment by zkat** [comment]
I mean, I'd rather it all be the same version...

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[b4ad265](https://github.com/NuGet/docs.microsoft.com-nuget/commits/b4ad26522aab99dab402de544251fd646b4ee9d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/dev-hengliu-change-example-nuspec.xsd/docs/create-packages/Creating-a-Package.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/creating-a-package?branch=pr-en-us-1915) |
[docs/create-packages/set-package-type.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/dev-hengliu-change-example-nuspec.xsd/docs/create-packages/set-package-type.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/set-package-type?branch=pr-en-us-1915) |
[docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/dev-hengliu-change-example-nuspec.xsd/docs/reference/nuspec.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/nuspec?branch=pr-en-us-1915) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C28%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202002282231487573-1915%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ANhdfkCQz%2ByYrrgdQbsIFeW4ekaIuvqVOMFMAPylqDY%3D&st=2020-02-28T22%3A27%3A29Z&se=2020-03-30T22%3A32%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by heng-liu** [comment]
> I mean, I'd rather it all be the same version...

Thanks! I agree. Since the .xsd files are not yet implemented, we'd better to keep it the same everywhere to avoid causing confusion. Fixed.

**Pull request merged**
