### PR TITLE
Revert "Update Readme allowlist"

### PR DESCRIPTION
**Pull request by emmyforeignet**
Reverts NuGet/docs.microsoft.com-nuget#3017

### CODE REVIEW

**Review by emmyforeignet — COMMENTED** [review]
gh pr checkout 3019
emmyforeignet:revert-3017-lyndaidaii-patch-1

**Review by emmyforeignet — COMMENTED** [review]
docs/nuget-org/package-readme-on-nuget-org.md

**Comment by emmyforeignet** [comment]
From 879abd9a8a03f0a327caccc786a957014b447091 Mon Sep 17 00:00:00 2001
From: emmyforeignet <125759388+emmyforeignet@users.noreply.github.com>
Date: Wed, 1 Mar 2023 19:38:25 +0100
Subject: [PATCH] Revert "Update Readme allowlist (#3017)"

This reverts commit 7ba803745bd0c6da281b53890e844e50af156415.
---
 docs/nuget-org/package-readme-on-nuget-org.md | 2 --
 1 file changed, 2 deletions(-)

diff --git a/docs/nuget-org/package-readme-on-nuget-org.md b/docs/nuget-org/package-readme-on-nuget-org.md
index 7867061d2..c49751501 100644
--- a/docs/nuget-org/package-readme-on-nuget-org.md
+++ b/docs/nuget-org/package-readme-on-nuget-org.md
@@ -56,7 +56,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * badges.gitter.im
 * bettercodehub.com
 * buildstats.info
-* caniuse.bitsofco.de
 * camo.githubusercontent.com
 * cdn.jsdelivr.net
 * cdn.syncfusion.com
@@ -66,7 +65,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * codefactor.io
 * coveralls.io
 * dev.azure.com
-* flat.badgen.net
 * github.com/.../workflows/.../badge.svg
 * gitlab.com
 * img.shields.io

**Comment by emmyforeignet** [comment]
From 879abd9a8a03f0a327caccc786a957014b447091 Mon Sep 17 00:00:00 2001
From: emmyforeignet <125759388+emmyforeignet@users.noreply.github.com>
Date: Wed, 1 Mar 2023 19:38:25 +0100
Subject: [PATCH] Revert "Update Readme allowlist (#3017)"

This reverts commit 7ba803745bd0c6da281b53890e844e50af156415.
---
 docs/nuget-org/package-readme-on-nuget-org.md | 2 --
 1 file changed, 2 deletions(-)

diff --git a/docs/nuget-org/package-readme-on-nuget-org.md b/docs/nuget-org/package-readme-on-nuget-org.md
index 7867061d2..c49751501 100644
--- a/docs/nuget-org/package-readme-on-nuget-org.md
+++ b/docs/nuget-org/package-readme-on-nuget-org.md
@@ -56,7 +56,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * badges.gitter.im
 * bettercodehub.com
 * buildstats.info
-* caniuse.bitsofco.de
 * camo.githubusercontent.com
 * cdn.jsdelivr.net
 * cdn.syncfusion.com
@@ -66,7 +65,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * codefactor.io
 * coveralls.io
 * dev.azure.com
-* flat.badgen.net
 * github.com/.../workflows/.../badge.svg
 * gitlab.com
 * img.shields.io

**Comment by emmyforeignet** [comment]
diff --git a/docs/nuget-org/package-readme-on-nuget-org.md b/docs/nuget-org/package-readme-on-nuget-org.md
index 7867061d2..c49751501 100644
--- a/docs/nuget-org/package-readme-on-nuget-org.md
+++ b/docs/nuget-org/package-readme-on-nuget-org.md
@@ -56,7 +56,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * badges.gitter.im
 * bettercodehub.com
 * buildstats.info
-* caniuse.bitsofco.de
 * camo.githubusercontent.com
 * cdn.jsdelivr.net
 * cdn.syncfusion.com
@@ -66,7 +65,6 @@ NuGet.org allows all images, including badges, from the following trusted domain
 * codefactor.io
 * coveralls.io
 * dev.azure.com
-* flat.badgen.net
 * github.com/.../workflows/.../badge.svg
 * gitlab.com
 * img.shields.io

**Comment by joelverhagen** [comment]
Hey @emmyforeignet, the comments here make it look like the GitHub CLI might be acting strangely for you. I'm going to close this PR.

**Pull request closed without merging**
