### PR TITLE
Document MSBuildSdk package type

### PR DESCRIPTION
**Pull request by robmen**

### CODE REVIEW

**Comment by robmen** [comment]
Feel free to edit this PR as appropriate. I was just made aware of this package type, and figured others would benefit from knowing about it as well.

**Comment by nkolev92** [comment]
https://github.com/NuGet/docs.microsoft.com-nuget/pull/2843 is an older with the same goal. 

cc @jeffkl

**Review by erdembayar — APPROVED** [review]

**Review by erdembayar — COMMENTED** [review]
Sorry, I didn't see there is other pending PR.

**Review by JonDouglas — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
