### PR TITLE
Update Index.md

### PR DESCRIPTION
**Pull request by anangaur**
It seems updating this page was missed. 

@chgill-MSFT, do merge it if there are no other issues.

### CODE REVIEW

**Comment by anangaur** [comment]
Docs Build status updates of commit _[3db4087](https://github.com/NuGet/docs.microsoft.com-nuget/commits/3db4087ff1fc40295666214e7bcb906e9f3190cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/release-notes/Index.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-5.6-release-notes/docs/release-notes/Index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/index?branch=pr-en-us-2047) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C21%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202005211425588161-2047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OLi3R6G8%2FYNKYVdKROsUtZwM8mlsIulGkuu%2FfgysxA0%3D&st=2020-05-21T14%3A21%3A45Z&se=2020-06-21T14%3A26%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rrelyea** [comment]
it wasn't in the original PR, but we mentioned in conversation, and i think @chgill-MSFT already fixed it as part of that PR's iterations.

image

**Comment by anangaur** [comment]
TOC is at 2 places :) This page is missing the 5.6 release notes

image

**Comment by anangaur** [comment]
Ping @chgill-MSFT

**Pull request merged**
