### PR TITLE
Add package push and delete examples

### PR DESCRIPTION
**Pull request by loic-sharma**
Depends on: https://github.com/NuGet/Samples/pull/45

Part of: https://github.com/NuGet/docs.microsoft.com-nuget/issues/787

### CODE REVIEW

**Review by zivkan — COMMENTED** [review]
This can't be validated until the samples PR is merged. Please re-request review once the preview link shows the working sample and the docs compiler no longer reports warnings/errors.

**Comment by nkolev92** [comment]
if you rebase on top of latest master it will clear some of the warnings the build is raising.

**Comment by loic-sharma** [comment]
@nkolev92  @zivkan Rebased, please re-review

**Review by zivkan — APPROVED** [review]
My comments are probably out of scope for your PR, hence I'm approving it anyway, but:
* The first set of examples in the doc are related to NuGet.Protocol, then there are 2 NuGet.Packaging examples, and then you've added two NuGet.Protocol examples at the end. I think all the NuGet.Protocol should be grouped together.
* I think that there should be NuGet.Protocol and NuGet.Packaging headers, and they should be `H2` level headers, so they appear in the "In this article" menu, making it quick for customers to skip straight to the package that they're interested in a sample for.

**Review by nkolev92 — APPROVED** [review]
Looks good. 

I agree with @zivkan's feedback about separating them by package. 
I am also ok with making that out of scope

**Comment by loic-sharma** [comment]
@zivkan Good idea, I added the two sections to the document

**Pull request merged**
