### PR TITLE
4.5 relnotes

### PR DESCRIPTION
**Pull request by anangaur**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/API/package-base-address-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/API/package-base-address-resource.md) | :white_check_mark:Succeeded | |
[docs/API/registration-base-url-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/API/registration-base-url-resource.md) | :white_check_mark:Succeeded | |
[docs/Consume-Packages/Configuring-NuGet-Behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Consume-Packages/Configuring-NuGet-Behavior.md) | :white_check_mark:Succeeded | |
[docs/Consume-Packages/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Consume-Packages/Dependency-Resolution.md) | :white_check_mark:Succeeded | |
[docs/Create-Packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Create-Packages/Creating-a-Package.md) | :white_check_mark:Succeeded | |
[docs/Release-Notes/NuGet-4.5-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Release-Notes/NuGet-4.5-RTM.md) | :white_check_mark:Succeeded | |
[docs/Schema/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Schema/nuspec.md) | :white_check_mark:Succeeded | |
[docs/Schema/project-json.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/anangaur-4.5-relnotes/docs/Schema/project-json.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C5%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201712050108266846-582%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mL9FnjHqwOnsC3lRy4i28PcO83kMNyx5aRUffB5wRnk%3D&st=2017-12-05T01%3A04%3A30Z&se=2018-01-05T01%3A09%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by anangaur** [comment]
I just added a new file https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Release-Notes/NuGet-4.5-RTM.md but on pull request i see other file chenges getting pulled in too. So for now I am going to directly edit the live branch with my changes.

**Comment by anangaur** [comment]
/cc: @kraigb @karann-msft See my comments above

**Comment by anangaur** [comment]
May be some issues on my machine. Submitted another clean one https://github.com/NuGet/docs.microsoft.com-nuget/pull/583

**Pull request closed without merging**
