### PR TITLE
Update Publish-a-package.md

### PR DESCRIPTION
**Pull request by xp44mm**

### CODE REVIEW

**Comment by anangaur** [comment]
Docs Build status updates of commit _[5acba83](https://github.com/xp44mm/docs.microsoft.com-nuget/commits/5acba83baa714ca111e97b99e276cfd1d73876df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/nuget-org/Publish-a-package.md](https://github.com/xp44mm/docs.microsoft.com-nuget/blob/patch-1/docs/nuget-org/Publish-a-package.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package?branch=pr-en-us-2068) | [Details](#user-content-894f5517-08b900d3)

<a id="894f5517-08b900d3"></a>
### [docs/nuget-org/Publish-a-package.md](https://github.com/xp44mm/docs.microsoft.com-nuget/blob/patch-1/docs/nuget-org/Publish-a-package.md)
 - **Line 66**: **[Warning-link-out-of-scope]** `````File 'quickstart/includes/publish-api-key.md' referenced by link '../quickstart/includes/publish-api-key.md' will not be built because it is not included in build scope`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C13%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202006130100055271-2068%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bd00rjAwRKyyAXO5HEGzohx8dGDYL951LhuCMe7heCk%3D&st=2020-06-13T00%3A55%3A40Z&se=2020-07-14T01%3A00%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JonDouglas** [comment]
@xp44mm With the strikeout you added in this PR, would you rather this just be omitted instead?

**Comment by xp44mm** [comment]
both is better than current obsolete state. use strikeout point out need more work to do.

**Comment by loic-sharma** [comment]
Thanks for your contribution! I've sent a pull request to remove this outdated content here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/2188

**Pull request closed without merging**
