### PR TITLE
Push live to get the offline book updated

### PR DESCRIPTION
**Pull request by Mikejo5000**

### CODE REVIEW

**Comment by anangaur** [comment]
Docs Build status updates of commit _[999808b](https://github.com/NuGet/docs.microsoft.com-nuget/commits/999808bccd729b6ccfe5600aa9ed8d6173a8f054)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/package-restore?branch=pr-en-us-2233) | [Details](#user-content-9251b79c-c3deec5c)
[docs/guides/analyzers-conventions.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/analyzers-conventions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/nuget/guides/analyzers-conventions?branch=pr-en-us-2233) | [Details](#user-content-d40f911f-c3deec5c)
[docs/guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/api/query-for-all-published-packages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages?branch=pr-en-us-2233) | [Details](#user-content-310e2dbd-c3deec5c)
[docs/TOC.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/package-restore?branch=pr-en-us-2233) |
[docs/release-notes/NuGet-5.8.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-5.8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-5.8?branch=pr-en-us-2233) |

<a id="9251b79c-c3deec5c"></a>
### [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
 - **Line 5, Column 12**: **[Warning-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'karann' is not a valid Microsoft alias.`````
 - **Line 145, Column 138**: **[Warning-file-not-found]** `````Invalid file link: '../../consume-packages/package-references-in-project-files.md'.`````
 - **Line 179, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops`````

<a id="d40f911f-c3deec5c"></a>
### [docs/guides/analyzers-conventions.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/analyzers-conventions.md)
 - **Line 5, Column 12**: **[Warning-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'karann' is not a valid Microsoft alias.`````
 - **Line 41, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="310e2dbd-c3deec5c"></a>
### [docs/guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/api/query-for-all-published-packages.md)
 - **Line 52, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202012151817312100-2233%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4qK0SdPklvd3rtf1OJHPy3HsPYmUY6bEVGVABCLj1CE%3D&st=2020-12-15T18%3A13%3A05Z&se=2021-01-15T18%3A18%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by anangaur** [comment]
Docs Build status updates of commit _[2c793bf](https://github.com/NuGet/docs.microsoft.com-nuget/commits/2c793bf87ca01906ff01d302737e21dae6e421a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/package-restore?branch=pr-en-us-2233) | [Details](#user-content-9251b79c-4d1f9920)
[docs/guides/analyzers-conventions.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/analyzers-conventions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/guides/analyzers-conventions?branch=pr-en-us-2233) | [Details](#user-content-d40f911f-4d1f9920)
[docs/guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/api/query-for-all-published-packages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages?branch=pr-en-us-2233) | [Details](#user-content-310e2dbd-4d1f9920)
[docs/TOC.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/package-restore?branch=pr-en-us-2233) |
[docs/release-notes/NuGet-5.8.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-5.8.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/release-notes/nuget-5.8?branch=pr-en-us-2233) |

<a id="9251b79c-4d1f9920"></a>
### [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
 - **Line 179, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops`````

<a id="d40f911f-4d1f9920"></a>
### [docs/guides/analyzers-conventions.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/analyzers-conventions.md)
 - **Line 41, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="310e2dbd-4d1f9920"></a>
### [docs/guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/api/query-for-all-published-packages.md)
 - **Line 52, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202012151831109608-2233%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qVUzVCc3trbmvfam7kySro37coM%2FT8DQT3OtzXoToY8%3D&st=2020-12-15T18%3A26%3A44Z&se=2021-01-15T18%3A31%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Mikejo5000** [comment]
@JonDouglas Jon, is it OK if you are the author on the NuGet docs now, replacing karan? The invalid author generates a warning now. If OK, I think I will also do a bulk update to fix this issue.

**Comment by Mikejo5000** [comment]
Merging to resolve offline book request. @JonDouglas for the other questions that came up (see previous comment).

**Pull request merged**
