### PR TITLE
channel9 links fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by JonDouglas** [comment]
@v-hearya Can we remove the `en-us` for localization reasons?

**Comment by v-hearya** [comment]
Closing the PR for now. Will revisit once requestor need it.

**Comment by JonDouglas** [comment]
Hi @v-hearya, we would like to take this PR, it just isn't localized. 

If you can update the PR to remove the `en-us` from links, we can merge.

**Comment by v-hearya** [comment]
> Hi @v-hearya, we would like to take this PR, it just isn't localized.
> 
> If you can update the PR to remove the `en-us` from links, we can merge.

@JonDouglas - en-us has been removed from url.

**Review by JonDouglas — APPROVED** [review]
Thank you for the contribution by fixing CH9 links!

**Pull request merged**
