### PR TITLE
Refresh NuGet get started articles for VS 2022 #3a

### PR DESCRIPTION
**Pull request by dksimpson**
Address review comments from @donnie-msft from merged PR: #2828.

This work is in accordance with [User Story 1973817](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1973817).

### CODE REVIEW

**Comment by dksimpson** [comment]
Hello @Mikejo5000 @nkolev92, @JonDouglas @zivkan, I've created a new PR to address the comments of @donnie-msft.

**Review by Mikejo5000 — APPROVED** [review]
Thanks!

**Review by donnie-msft — APPROVED** [review]
Looks good, thanks for going back for my review!

**Comment by dksimpson** [comment]
@Mikejo5000 Looks like we can merge this one.

**Comment by dksimpson** [comment]
#sign-off

**Review by zivkan — APPROVED** [review]

**Pull request merged**
