### PR TITLE
Change the metadata for package reference from exclude to excldue assets

### PR DESCRIPTION
**Pull request by nkolev92**
The attribute for package reference to exclude libraries is wrong. 

It needs updated from Exclude="All" to ```ExcludeAssets="All"```
For reference: 
Look at: 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
  
Fixes: https://github.com/NuGet/Home/issues/6399
//cc
@kraigb @karann-msft @anangaur

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/NuGet/docs.microsoft.com-nuget, working directory: W:\npud-s, target branch: live, target branch commit: c27e565de485cbe836e6c2a66e44a50b35b487ff, source branch: b6c99018ca9ddad15b1052ee94ece2d4/nkolev92-fixexclude, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C9%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201801090053272099-641%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZTM8zD1mKVRll%2FLPTrrVKcjnUL%2ByX0%2FOKlYZ0NqvZDk%3D&st=2018-01-09T00%3A48%3A40Z&se=2018-02-09T00%3A53%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit a8c933899ffabc1ee3e9d8466df180dbc46d4db4 in branch nkolev92-fixexclude of repository https://github.com/nkolev92/docs.microsoft.com-nuget into branch live (commit 51eae111f0fec4fbb21e5e702629beaa3e8abc2b)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201801101757326867-641%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sa65bHeNo%2FXqlx8qIe%2BZxd5piBuwLTRcvLN7OQOH9zg%3D&st=2018-01-10T17%3A52%3A38Z&se=2018-02-10T17%3A57%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Consume-Packages/Dependency-Resolution.md](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/nkolev92-fixexclude/docs/Consume-Packages/Dependency-Resolution.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201801101758533046-641%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vrs49kV5DY6PiSdNRMeL6ij0OnjNkZpJr7uShG%2Bbhn4%3D&st=2018-01-10T17%3A54%3A42Z&se=2018-02-10T17%3A59%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nkolev92** [comment]
Thanks for the taking care of this @kraigb

**Pull request merged**
