### PR TITLE
Merge 'master' branch into 'live'

### PR DESCRIPTION
**Pull request by loic-sharma**
Includes:

* Update GitHub Usage wording as per CELA recommendations (#1784)

### CODE REVIEW

**Comment by joelverhagen** [comment]
Is there a playbook for deploying docs somewhere?

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[f6bff5e](https://github.com/NuGet/docs.microsoft.com-nuget/commits/f6bff5ed4573357661e602b094ade5a3da23830a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1786) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C19%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911192308275236-1786%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sOXNaq%2FZgl5ergO36z7wGcx7i%2BEHrcjiz0eBwg%2FNefU%3D&st=2019-11-19T23%3A04%3A41Z&se=2019-12-20T23%3A09%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[5d986b2](https://github.com/NuGet/docs.microsoft.com-nuget/commits/5d986b27fd715de27feead2ada3f6dbb75e92f69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1786) |
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1786) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C20%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911202150105487-1786%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1pKW125kmP%2FU855pwF2AZIkvBVnI3Yx0bCIgUxxLsA8%3D&st=2019-11-20T21%3A46%3A18Z&se=2019-12-21T21%3A51%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[088d2c0](https://github.com/NuGet/docs.microsoft.com-nuget/commits/088d2c024d93c74db56cc2cab07f07c184aa5041)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages?branch=pr-en-us-1786) |
[docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg?branch=pr-en-us-1786) |
[docs/create-packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/create-packages/symbol-packages?branch=pr-en-us-1786) |
[docs/nuget-org/individual-accounts.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/individual-accounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts?branch=pr-en-us-1786) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C20%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201911202151206797-1786%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D9a5r0h%2F%2BFO5S9A0FqI5gUtY8MDy21h%2F%2B9wmBQGW6IA%3D&st=2019-11-20T21%3A47%3A35Z&se=2019-12-21T21%3A52%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
