### PR TITLE
ContinueOnError new option

### PR DESCRIPTION
**Pull request by donnie-msft**
Added detail about new ContinueOnError option, as well as examples. Corrected "-s" in another example which is an ambiguous flag.

### CODE REVIEW

**Comment by karann-msft** [comment]
Docs Build status updates of commit _[82ca8b4](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1402/commits/82ca8b43c3209997db97e93ccb1998055e457235)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/tools/cli-ref-push.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/donnie-msft-patch-1/docs/tools/cli-ref-push.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/tools/cli-ref-push?branch=pr-en-us-1402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201904151901208628-1402%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Boo4fI19SwNjsbsX21EBOLPpzPaYQkRfuw6QlzPnMNc%3D&st=2019-04-15T18%3A57%3A32Z&se=2019-05-16T19%3A02%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by donnie-msft** [comment]
Closing because in our meeting we changed the naming and functionality.

**Comment by karann-msft** [comment]
Hey @donnie-msft - feel free to self assign docs PRs.

**Comment by donnie-msft** [comment]
> Hey @donnie-msft - feel free to self assign docs PRs.
You specifically asked me to add you to this PR, but I see now there is a Reviewer option which must be what you want.

**Pull request closed without merging**
