### PR TITLE
Improve the catalog API guide to mention the pre-release SDK available on MyGet

### PR DESCRIPTION
**Pull request by joelverhagen**
Review URL:
https://review.docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages?branch=jver-polish-guide

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/API/catalog-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/API/catalog-resource.md) | :white_check_mark:Succeeded | |
[docs/Guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/Guides/api/query-for-all-published-packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201711102330095313-562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=poLDsy9vf8Y2h92fiMdXSrjbKfVN4J%2Fl7%2BCuw7PI3FE%3D&st=2017-11-10T23%3A25%3A57Z&se=2017-12-11T23%3A30%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/API/catalog-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/API/catalog-resource.md) | :white_check_mark:Succeeded | |
[docs/Guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/Guides/api/query-for-all-published-packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201711102339141675-562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YRb43GY0cnM%2FKRFvCJ3QY324HA1zC4P61fQw32%2F4eIo%3D&st=2017-11-10T23%3A35%3A08Z&se=2017-12-11T23%3A40%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/API/catalog-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/API/catalog-resource.md) | :white_check_mark:Succeeded | |
[docs/Guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/Guides/api/query-for-all-published-packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201711102340074170-562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0L7hcNA70vZ9kdKO8rE9dk2x0Yd0yVfv2jKok3bkDoM%3D&st=2017-11-10T23%3A36%3A26Z&se=2017-12-11T23%3A41%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/API/catalog-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/API/catalog-resource.md) | :white_check_mark:Succeeded | |
[docs/Guides/api/query-for-all-published-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/jver-polish-guide/docs/Guides/api/query-for-all-published-packages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C13%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201711131931088871-562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FwkxKUqfTABzBsUyx67eqhCjhMpGFd%2BRzaXLfUSHW3w%3D&st=2017-11-13T19%3A27%3A53Z&se=2017-12-14T19%3A32%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@joelverhagen Is this ready to merge?

**Comment by joelverhagen** [comment]
@kraigb, yup, :shipit:

**Pull request merged**
