### PR TITLE
Legal updates from CELA

### PR DESCRIPTION
**Pull request by Taojunshen**
CELA has provided replacement licence files which include separate licenses for CC and code snippets. The Content Engineering Team has been tasked with replacing the license files on all existing repos. The changes to the README file must be at the top of the file to be recognized by license scanners.
 
Please see this communication for more details: [Legal Update Notice](https://microsoft.sharepoint.com/teams/STBCSI/e/CE/_layouts/15/guestaccess.aspx?guestaccesstoken=m4R%2fQ5Es3YlfV%2fUTJ09pb8x50MXjJNNO20%2b9YHpi5%2bo%3d&docid=2_0a46b1b0a931049e5afab07102ab5c0df&rev=11)
 
Please accept the PR as soon as possible.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LICENSE](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/LICENSE) | :white_check_mark:Succeeded | |
[LICENSE-CODE](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/LICENSE-CODE) | :white_check_mark:Succeeded | |
[README.md](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/README.md) | :white_check_mark:Succeeded | |
[ThirdPartyNotices](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/ThirdPartyNotices) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201703221651308084-230%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@karann-msft Can you review and verify these changes?

**Comment by karann-msft** [comment]
@Taojunshen nuget falls under the .NET Foundation. Has that been accounted for in update that you have suggested?

**Comment by v-anpasi** [comment]
@karann-msft, Thanks for raising this issue. I will look into it.

**Comment by karann-msft** [comment]
@Taojunshen @v-anpasi I had started a thread where CELA has responded with what needs to be done here. Can you please update the PR to incorporate that feedback.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/NuGet/docs.microsoft.com-nuget, working directory: W:\wvsz-s, target branch: master, target branch commit: 989b7ae57df5667bacba3cb1cf1f9be064596a87, source branch: 503b777c1a11ef419cd59574a7c10d46/CELA-updates, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C29%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201703291445384812-230%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LICENSE](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/LICENSE) | :white_check_mark:Succeeded | |
[LICENSE-CODE](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/LICENSE-CODE) | :white_check_mark:Succeeded | |
[README.md](https://github.com/Taojunshen/docs.microsoft.com-nuget/blob/CELA-updates/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C29%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201703291538040859-230%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
Does anything need to be done with this PR? Otherwise, let's close it without merging.

**Pull request closed without merging**
