### PR TITLE
Mention packagesourcemapper tool in packagesourcemapping feature

### PR DESCRIPTION
**Pull request by erdembayar**
Somehow this PR picking up commits from other [PR](https://github.com/NuGet/docs.microsoft.com-nuget/pull/2840/commits). 
Probably should I have rebased my branch or bad timing for making change?

### CODE REVIEW

**Comment by nkolev92** [comment]
@erdembayar The problem isn't you, the problem is that the PR you linked was squashed

**Comment by erdembayar** [comment]
> @erdembayar The problem isn't you, the problem is that the PR you linked was squashed

I see, what to do now? Could we still merge this PR?

**Comment by nkolev92** [comment]
2 options I can think of.

- We merge this PR as is.
- We rewrite the history of live.

I'd include @JonDouglas here. I don't know if the 2nd option is a good one.

**Comment by JonDouglas** [comment]
We should only be merging into `main` with rare or small additions that can be committed directly to `live`.

The flow today is:

- contributions -> `main`.

- `main` -> `live` a couple times a month.

This PR is adding quite a few things it probably shouldn't. Perhaps a fresh PR would be better in this case and just close this one out.

**Comment by nkolev92** [comment]
I think this PR is effectively adding 2 changes only. 

The issues is that live contains a squashed commit which is what's really causing the problem, so git can't detect the changes correctly.

**Comment by erdembayar** [comment]
> We should only be merging into `main`. Sometimes with rare or small additions that can be committed directly to `live`.
> 
> The flow today is:
> 
> * contributions -> `main`.
> * `main` -> `live` a couple times a month.
> 
> This PR is adding quite a few things it probably shouldn't. 

Could you clarify what are those few things? It's just my changes on top of existing changes. I understood correctly previous PR was squash merged so we lost history, look like we shouldn't squash merge on this repo.

**Comment by JonDouglas** [comment]
I may have squashed with the GitHub UI then. let's just overwrite live and start a fresh? i.e. option 1.

**Comment by nkolev92** [comment]
So just to confirm, option 1 is:

> We merge this PR as is.

? 

Do you want to merge this to live or should we wait?

**Review by JonDouglas — APPROVED** [review]

**Comment by JonDouglas** [comment]
@nkolev92 Yeah. I don't see what we would be waiting for at the moment. I don't think this would cause any issues.

**Comment by erdembayar** [comment]
@JonDouglas  @nkolev92 
Could someone merge it for me? It says "You're not authorized to merge this pull request".

**Pull request merged**
