### PR TITLE
document extension points in the pack target

### PR DESCRIPTION
**Pull request by rohit21agrawal**
CC: @kraigb

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/msbuild-targets.md](https://github.com/rohit21agrawal/docs.microsoft.com-nuget/blob/patch-5/docs/reference/msbuild-targets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C22%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201803222344232136-794%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w2QbX1IVlikMsJ3GPobFSJXufkHrabCdxwVBlC5%2Fxwg%3D&st=2018-03-22T23%3A52%3A03Z&se=2018-04-22T23%3A57%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@rohit21agrawal I made an edit pass on the material. Please review.

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/msbuild-targets.md](https://github.com/rohit21agrawal/docs.microsoft.com-nuget/blob/patch-5/docs/reference/msbuild-targets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C23%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201803231744088997-794%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=onJN8Ju5IPjP1R01Adle1VBSWHjnAqzm8bBCGe9nQHw%3D&st=2018-03-23T17%3A40%3A45Z&se=2018-04-23T17%3A45%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rohit21agrawal** [comment]
@kraigb looks good, thanks!

**Pull request merged**
