### PR TITLE
June 2022 docs merge

### PR DESCRIPTION
**Pull request by kartheekp-ms**

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Comment by erdembayar** [comment]
Please merge at earliest convenience. I need to close tracking issues.

**Comment by erdembayar** [comment]
@JonDouglas @kartheekp-ms 
Could we merge this now?

**Comment by kartheekp-ms** [comment]
I don't have permissions to merge this PR. @anangaur @chgill-MSFT @nkolev92 @clairernovotny - Please review this PR whenever you have a minute and help me merging this PR as I don't have permissions.

cc @erdembayar

**Comment by nkolev92** [comment]
I'll start an e-mail thread to see if we should expand the permissions.

**Pull request merged**
