### PR TITLE
Replace Team Services with Azure DevOps

### PR DESCRIPTION
**Pull request by pascalberger**
Replace Team Services with Azure DevOps

### CODE REVIEW

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/policies/NuGet-FAQ.md](https://github.com/pascalberger/docs.microsoft.com-nuget/blob/patch-3/docs/policies/NuGet-FAQ.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/policies/nuget-faq?branch=pr-en-us-1196) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C29%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201811291943249726-1196%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fyeLunsKKQ1URsLK90VlrGGKxe4yQM63PNUr%2BLNr9xg%3D&st=2018-11-29T19%3A39%3A29Z&se=2018-12-30T19%3A44%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zivkan** [comment]
Should the `Visual Studio Team Services` at the beginning of the same line be changed as well?

**Comment by pascalberger** [comment]
@zivkan Update this and another occurrence

**Comment by karann-msft** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/policies/NuGet-FAQ.md](https://github.com/pascalberger/docs.microsoft.com-nuget/blob/patch-3/docs/policies/NuGet-FAQ.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/policies/nuget-faq?branch=pr-en-us-1196) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C1%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C201812010852014853-1196%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9f7GLRrgum28BlAFDoMfH7DPnvZGYI8In69IvGlJyec%3D&st=2018-12-01T08%3A48%3A00Z&se=2019-01-01T08%3A53%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
